### ISSUE TITLE
Use lyrics from Friday I'm In Love

### ISSUE THREAD

**Issue by oniony** [ButchersBoy/Dragablz#10]
The screencast is currently using lyrics from the nursery rhyme *Monday's Child*. I think this demonstration would be much improved by switching to lyrics from The Cure's *Friday I'm In Love*.

**Comment by ButchersBoy** [comment]
How about some Craig David?

**Comment by ButchersBoy** [comment]
I met this tab on Monday...
Fell in love on Tuesday...
We were making clicks by Wednesday...

**Comment by ButchersBoy** [comment]
...and Thursday Friday Saturday, crashed on Sunday.

**Comment by oniony** [comment]
[Inspiration](https://coolrain44.wordpress.com/2009/06/05/songs-about-days-of-the-week/)
