### ISSUE TITLE
Tab Order

### ISSUE THREAD

**Issue by RickStrahl** [ButchersBoy/Dragablz#101]
This is more of a question than an issue, but I've been looking through discussions on StackOverflow regarding Tab ordering, but found that all are referring to tab bindings which I am not actually doing in this case.

Basically I need to capture the actual tab order when the app is shutting down, but there appears to be no way to capture or manipulate the actual order. I mucked around with PositionMonitor but gave up on that as that doesn't really fit my need. I even went as far as trying to look at the X position on screen, couldn't get that to work either as I can't seem to get a relative position to another element.

What do you suggest is the best way to get the tab order programmatically?

**Comment by ButchersBoy** [comment]
_If_ you are using the Layout (to create window splitting) as in the picture below, use ```Layout.Query ``` as illustrated in the Layout Info tab in the demo in the main source.

![image](https://cloud.githubusercontent.com/assets/658107/15568345/4d1b68b0-2323-11e6-9bb1-d94458badf1f.png)

Otherwise; yes you can use the PositionMonitor (maybe you'd have to cache the ordering until app shut down). However, I need to make that easier, as there's a bit of logic slightly hidden from the consumer, which I can open up (leave this issue open and I'll do that).

As for "manipulating" items, you have some static helper methods which will work across all loaded instances:

``` public static IEnumerable<TabablzControl> GetLoadedInstances() ```

``` public static void AddItem(object item, object nearItem, AddLocationHint addLocationHint) ```

``` public static void SelectItem(object item) ```

**Comment by RickStrahl** [comment]
This might be a dumb question, but why aren't the drag rearrangements automatically updating the item indexes and actual order of items? I know it's probably not easy for all the drag and tear-off scenarios but I would expect that to be the default behavior. Or if not that some sort of attached property that lets you query the order. Having to delve into physical positions is pretty low level for something that's probably quite common.

**Comment by RickStrahl** [comment]
Can you give or point at an example on how to hook up the PostionMonitor programmatically? I can't get it to fire doing this:

```
tab.SetValue(DragablzItemsControl.PositionMonitorProperty, TabPositionMonitor);
```
where it's hooked up to a form property like this:

```csharp
TabPositionMonitor = new HorizontalPositionMonitor();
TabPositionMonitor.LocationChanged += TabPositionMonitor_LocationChanged;
```

the handler is never fired.

**Comment by ButchersBoy** [comment]
Sorry, that was bum info I have you, the position monitor isn't readily available...until now...I've added a new method on the tab control:

``` .GetOrderedHeaders() ```

**Comment by RickStrahl** [comment]
Awesome! Works great and that's a really useful feature to have. Thank you for the quick turnaround.

Not to take away from that but wouldn't it have been better to name it GetOrderedItems() since it is returning the actual (tab) items in the enumeration?

**Comment by ButchersBoy** [comment]
Yeah...I was torn back and forth...I  might change it, we are less than v1 so can afford to  muck about with the API...
