### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by RickStrahl** [ButchersBoy/Dragablz#102]
Looks like Tooltips on tab items have no effect. Is this supported?

Also context menu is not working either, but that's less of a concern.

BTW, finding these as I'm moving over existing tabs from MahApps. Other than these (so far anyway) everything just worked as is without any changes which is pretty awesome.

**Comment by ButchersBoy** [comment]
Are you setting them directly on a TabItem?

**Comment by RickStrahl** [comment]
Yes.

**Comment by RickStrahl** [comment]
Any word on this? This is the one thing that would be really useful in Markdown Monster: Be able to see the underlying file name when hovering over a tab (a la Sublime).

**Comment by ButchersBoy** [comment]
I'll try and have a look over this week.

**Comment by RickStrahl** [comment]
Thanks James  - I wasn't trying to be pushy. Appreciate all the work you're doing with this excellent library. Making me look good :-)
Aloha.

**Comment by ButchersBoy** [comment]
No problem.  And thanks 😃.  Big football competition in Europe at the moment...bit distracting 😃

**Comment by RickStrahl** [comment]
Awesome! Works great!
