### ISSUE TITLE
Docking MDI?

### ISSUE THREAD

**Issue by picrap** [ButchersBoy/Dragablz#106]
Hi,

it is possible to dock MDI items (in a similar way to tabs)?

**Comment by ButchersBoy** [comment]
Kind of.  An MDI item can be dropped into a tab, and then take a look at the SideItems project in here: https://github.com/ButchersBoy/DragablzSamplez

**Comment by picrap** [comment]
This project does not exist... In the `*WindowApps` projects there is an MDI which can be placed in a new window, but not docked. I guess there is nothing more than this?
Thanks for quick answer (even if ... https://twitter.com/James_Willock/status/737919141454225408 :laughing: )

**Comment by ButchersBoy** [comment]
![image](https://cloud.githubusercontent.com/assets/658107/15704631/7a316df8-27e3-11e6-90f3-20924f570bc3.png)

**Comment by picrap** [comment]
`SidePanels`, not `SideItems`. And I couldn't find any MDI document in it. Nevermind, I have my answer. Thanks.

**Comment by ButchersBoy** [comment]
Sorry :)

**Comment by picrap** [comment]
Don't be! Dragablz is great anyway.
