### ISSUE TITLE
how i add a new tab?

### ISSUE THREAD

**Issue by avrAhituv** [ButchersBoy/Dragablz#108]
I wrote this code:
`  INewTabHost<Window> IInterTabClient.GetNewHost(IInterTabClient interTabClient, object partition, TabablzControl source)
        {
            var view = new UserControl1();
            return new Dragablz.NewTabHost<Window>(view,---------); 
        }`
and I don't know what I should write a second parameter?
Thanks!!

**Comment by ButchersBoy** [comment]
Hi, I think you are misunderstanding the purpose of ```IInterTabClient```.  That (optional) interface is for providing new _Windows_, not new tabs.

To add a new tab, either addit via ItemsSource, Items, or one of the helpers:

https://github.com/ButchersBoy/Dragablz/blob/master/Dragablz/TabablzControl.cs#L106

or

https://github.com/ButchersBoy/Dragablz/blob/master/Dragablz/TabablzControl.cs#L106

**Comment by francisrc** [comment]
First, thanks for your control.

I'm a newbie in WPF and actually I'm facing some difficult to add new tab by using the helpers. How I can find the nearItem?
Regards
