### ISSUE TITLE
Allow the ability to disable tab dragging?

### ISSUE THREAD

**Issue by Pyroglyph** [ButchersBoy/Dragablz#115]
I know that dragging tabs is the defining feature of this project, but I only use Dragablz for it's Material Design tabs. I don't want my users to be able to rearrange tabs on my app, but there is no way to disable them so I'm a bit stuck. Any workarounds or alternatives?

**Comment by ButchersBoy** [comment]
https://github.com/ButchersBoy/Dragablz/blob/master/Dragablz/TabablzControl.cs#L331

**Comment by ChemsoDev** [comment]
@NZSmartie thx dude u saved my day. this is the last post I was intending to read before I move onto another pkg LMAO
