### ISSUE TITLE
rename tab header

### ISSUE THREAD

**Issue by tthieu36** [ButchersBoy/Dragablz#116]
How to rename tab header from UserControl (from IntroducePage.xaml to Tab contain it)?
[https://github.com/ButchersBoy/DragablzSamplez/tree/master/DragablzWindowApp](url)

**Comment by ButchersBoy** [comment]
...this very much depends on your code base; if you are using MVVM, standard TabItems.  But it the tab header content is bindable in the standard WPF fashion; it will update to the source which you provide it.
