### ISSUE TITLE
Get item index from DragablzItemsControl after ordering

### ISSUE THREAD

**Issue by SilverDragon135** [ButchersBoy/Dragablz#118]
Hi, how can I determine the index of the item? If I switched first and second item, in DragablzItemsControl. Items [0] was returned second item, so I'm confused how to get the first item in collection how it is displayed.

**Comment by ButchersBoy** [comment]
Use a ``` PositionMonitor ``` or ``` TabablzControl.GetOrderedHeaders() ```

**Comment by SilverDragon135** [comment]
Sorry if I don´t understand it properly. But in dragablz:DragablzItemsControl is not GetOrderedHeaders() accessible, what is obvius, because you reffer to TabablzControl. And PositionMonitor force me to track position of every item to determine their position in collection, so it is little more complicated than system in TabablzControl and I´m curious if it is not possible to implement similar method (GetOrderedHeaders()) there.

**Comment by SilverDragon135** [comment]
Ok, never mind. Possible solution is to add to view invisible thumb and create properties in TabablzControl: 

`<dragablz:TabablzControl.HeaderItemsOrganiser>
                    <dragablz:VerticalOrganiser></dragablz:VerticalOrganiser>
                </dragablz:TabablzControl.HeaderItemsOrganiser>
                
               <dragablz:TabablzControl.HeaderItemTemplate>
                    <DataTemplate DataType="{x:Type view:WaveView}">
                        <ContentControl Width="{Binding ActualWidth, ElementName=TabControl_Waves}" Content="{Binding Content}"/>
                    </DataTemplate>
                </dragablz:TabablzControl.HeaderItemTemplate>
                <TabControl.ItemTemplate>
                    <DataTemplate DataType="{x:Type view:WaveView}">
                    </DataTemplate>
                </TabControl.ItemTemplate>
                <TabControl.ContentTemplate>
                    <DataTemplate DataType="{x:Type view:WaveView}">
                    </DataTemplate>
                </TabControl.ContentTemplate>`
This way I have possibility to switch items in menu and determine with GetOrderedHeaders() postition of each item. (Maybe datatype is not necessary in content and item template... )

**Comment by ButchersBoy** [comment]
Are you running latest? Because the method of already there.

**Comment by SilverDragon135** [comment]
0.0.3.169... I use nuget package.
