### ISSUE TITLE
Header is not selected when select tabitem programmatically

### ISSUE THREAD

**Issue by kogare** [ButchersBoy/Dragablz#12]
Content changed but the header is not selected when using aTabItem.IsSelected = true; via code behind.

Thanks for great control

**Comment by ButchersBoy** [comment]
ok...taking a look...

**Comment by kogare** [comment]
whoa fast reply, it actually doesn't work when I put it in this statement, sorry for incomplete information

foreach (Dragablz.TabablzControl tabablzControl in Controllers.Windows.Windows.FindVisualChildren<Dragablz.TabablzControl>(this))
                {
                    foreach (TabItem aTabItem in tabablzControl.Items)
                    {
                        if (aTabItem.Name.Equals("aTabItem"))
                        {
                            aTabItem.IsSelected = true;

                            masterDataPopup.IsOpen = false;
                        }
                    }
                }

**Comment by ButchersBoy** [comment]
You caught me at a good time, I was just getting on the compute!

**Comment by kogare** [comment]
ah cool.. also when adding new tabitem via code and then selecting it via selectedindex generate same issue, content changed but the header still selecting first tabitem. here's my code.

TabItem aTabItem = new TabItem();
 aTabItem.Name = "aTabItem";
 aTabItem.Header = "Second Tab";
 aTabItem.AllowDrop = true;

  mainTabControl.Items.Insert(mainTabControl.Items.Count, aTabItem);
  mainTabControl.SelectedIndex = mainTabControl.Items.Count - 1;

cheers..

**Comment by ButchersBoy** [comment]
OK, same fix fixes both problems.  Small thing though, when you do .Insert(), TabablzControl is "cleverly" putting the new tab next to the currently selected tab (and not at the end which is kinda implied by your example).  If this is an issue for you raise another issue and I'll take a look in due course.

Fix is checked into GitHub and look for build 0.0.0.101 on NuGet.  Let me know if it works for you and I'll close the issue.

Thanks,

James

**Comment by kogare** [comment]
Great, I can now select TabItem properly with both IsSelected and SelectedIndex.
Do you mean that index parameter in .Insert() doesn't have any effect, adding new TabItem will put it straight to the next of current selected tab ignoring index parameter?

**Comment by ButchersBoy** [comment]
Yep that's what I meant. I close this issue.
