### ISSUE TITLE
TabStripPlacement="Left" not working

### ISSUE THREAD

**Issue by robertmuehsig** [ButchersBoy/Dragablz#120]
I seems that TabStripPlacement="Left" is not supported. This code:

```
<Window x:Class="WpfApplication19.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApplication19"
        xmlns:dragablz="http://dragablz.net/winfx/xaml/dragablz"
        mc:Ignorable="d"
        Title="MainWindow" Height="350" Width="525">
    <dragablz:TabablzControl TabStripPlacement="Left">
        <TabItem Header="HELLO">
            <TextBlock HorizontalAlignment="Center" VerticalAlignment="Center">Hello World</TextBlock>
        </TabItem>
        <TabItem Header="MATERIAL">
            <TextBlock HorizontalAlignment="Center" VerticalAlignment="Center">Material Design</TextBlock>
        </TabItem>
        <TabItem Header="DESIGN">
            <TextBlock HorizontalAlignment="Center" VerticalAlignment="Center">Looks Quite Nice</TextBlock>
        </TabItem>
    </dragablz:TabablzControl>
</Window>
```

Will produce this:

![image](https://cloud.githubusercontent.com/assets/756703/17896767/144d3840-6952-11e6-94f6-144417de8f2f.png)

I found an [older](https://github.com/ButchersBoy/Dragablz/issues/16) issue, but the workaround there seems not to work anymore (I'm not doing anything) :

![gif](https://cloud.githubusercontent.com/assets/756703/17896908/8cb9a2c8-6952-11e6-8764-1362b886dc14.gif)

**Comment by ButchersBoy** [comment]
Left is only currently implemented when applying the material design style...are you wanting to use this style or another (using your posted XAML the default template/style will be applied).

**Comment by robertmuehsig** [comment]
I have a pretty basic style for TabItems that I would like to keep. The fancy drag'n'drop (with the supported "this is a fixed tabitem") is what I was looking for.

**Comment by ButchersBoy** [comment]
OK...so the code is in place for "Left", but the template isn't.  _Should_ be a case of porting some of the stuff done for the MatDesign template back into the default template, but bringing the XAML in line with the default template look and feel...

I can probably have a go later this week (poke me on Friday), or you can raise a PR.

**Comment by ButchersBoy** [comment]
Basic template should now work:

![dragablzleft](https://cloud.githubusercontent.com/assets/658107/18002562/8cdacb62-6b80-11e6-8130-ff0461698d9b.gif)
