### ISSUE TITLE
use for dragablz

### ISSUE THREAD

**Issue by pps83** [ButchersBoy/Dragablz#121]
Hi,

this isn't an issue report. I'm was looking for some project that implements chrome-style tabs, and the reason for that: I'm thinking to add tabbed functionality to putty (in a way what [clover3](http://ejie.me/) did to explorer). I recall a few years ago I came across some project that ripped of tabbing code from chromium and made a standalone lib out of it, but cannot find it now.
Your lib seems to do similar tab control, but it's not c/c++, perhaps you can take putty code and combine them together and get universal glory for finally getting it done right? :)

**Comment by ButchersBoy** [comment]
Hi,

This library is _very_ specific to WPF and the .Net Framework.  I don't think I'm the man to make this happen :)
