### ISSUE TITLE
Exception when I tear off a tab

### ISSUE THREAD

**Issue by AnthonyLHOMME** [ButchersBoy/Dragablz#127]
My TabablzControl is in UserControl and when I try to drag out a tab, I got an exception (I can reorder fine).

My MainWindow
```
<Window x:Class="Satroem.Views.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:prism="http://prismlibrary.com/"
        prism:ViewModelLocator.AutoWireViewModel="True"
        xmlns:resources="clr-namespace:Satroem.Resources"
        WindowStartupLocation="CenterScreen" FontFamily="Calibri"
        Title="Satroem" Height="720" Width="1280">
    <ContentControl prism:RegionManager.RegionName="{x:Static resources:RegionNames.ContentRegion}" />
</Window>
```

My UserControl
```
<UserControl x:Class="Satroem.Views.ISLoc.ISLocView"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:resources="clr-namespace:Satroem.Resources"
             xmlns:dragablz="clr-namespace:Dragablz;assembly=Dragablz"
             xmlns:dockablz="clr-namespace:Dragablz.Dockablz;assembly=Dragablz"
             xmlns:prism="http://prismlibrary.com/"
             prism:ViewModelLocator.AutoWireViewModel="True"
             mc:Ignorable="d">
        <Grid x:Name="container">
            <dockablz:Layout >
                <dragablz:TabablzControl BorderThickness="0" Margin="0,-1,0,1" ConsolidateOrphanedItems="True" SelectedIndex="{Binding SelectedTab}">
                    <dragablz:TabablzControl.InterTabController>
                        <dragablz:InterTabController />
                    </dragablz:TabablzControl.InterTabController>

                    <TabItem Header="Données">
                        <ContentControl prism:RegionManager.RegionName="{x:Static resources:RegionNames.TabDataRegion}" />
                    </TabItem>
                    <TabItem Header="Cartographie">
                        <ContentControl prism:RegionManager.RegionName="{x:Static resources:RegionNames.TabMapRegion}" />
                    </TabItem>
                    <TabItem Header="Résultats">
                        <ContentControl prism:RegionManager.RegionName="{x:Static resources:RegionNames.TabResultRegion}" />
                    </TabItem>

                </dragablz:TabablzControl>
            </dockablz:Layout>
        </Grid>
</UserControl>
```

My exception
```
An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll
Exception has been thrown by the target of an invocation.
```

**Comment by ButchersBoy** [comment]
Inner Exception?

**Comment by AnthonyLHOMME** [comment]
I can't have more details

**Comment by ButchersBoy** [comment]
There will be an InnerException. I will hazard a guess it will say something like "Unable to ascertain tab control".  Because whatever your Prism set-up is doing, a new TabablzControl isn't getting created when a new Window is getting created.  No new tab control, no cigar.

**Comment by AnthonyLHOMME** [comment]
How can I have details of InnerException?

**Comment by ButchersBoy** [comment]
![image](https://cloud.githubusercontent.com/assets/658107/19602030/82be2346-97a3-11e6-944a-57c3b0a5252b.png)

**Comment by AnthonyLHOMME** [comment]
![capture](https://cloud.githubusercontent.com/assets/8833722/19602149/559575a0-97ac-11e6-91e3-f121b0067257.PNG)

**Comment by ButchersBoy** [comment]
Make sure you have Break On All Error set.

![image](https://cloud.githubusercontent.com/assets/658107/19602221/52d30b0a-97a4-11e6-8c0f-8068f3d8087e.png)

Otherwise, catch the Exception in code, and grab the ``` exc.InnerException ```

**Comment by AnthonyLHOMME** [comment]
But I don't know where the exception is triggered

**Comment by ButchersBoy** [comment]
![image](https://cloud.githubusercontent.com/assets/658107/19602507/60fd8e98-97a5-11e6-8419-736f87a94d26.png)

**Comment by AnthonyLHOMME** [comment]
no change

**Comment by ButchersBoy** [comment]
May try catching the unhandled exception.

http://stackoverflow.com/questions/1472498/wpf-global-exception-handler

**Comment by AnthonyLHOMME** [comment]
Yes I got the inner exception

```
Unable to ascrtain tab control.
At Dragablz.DefaultInterTabClient.GetNewHost(IInterTabClient interTabClient, Object partition, TabablzControl source) in DefaultInterTabClient.cs:line 21
At Dragablz.TabablzControl.MonitorBreach(DragablzDragDeltaEventArgs e) in TabablzControl.cs:line 1195
At Dragablz.TabablzControl.ItemDragDelta(Object sender, DragablzDragDeltaEventArgs e) in TabablzControl.cs:line 1112
```

**Comment by ButchersBoy** [comment]
> There will be an InnerException. I will hazard a guess it will say something like "Unable to ascertain tab control". Because whatever your Prism set-up is doing, a new TabablzControl isn't getting created when a new Window is getting created. No new tab control, no cigar.

You have to make sure a TabablzControl is created as soon as your Window is (re)created.  Otherwise the drag operation cannot continue.  You may want to consider creating a custom IInterTabClient.

**Comment by AnthonyLHOMME** [comment]
I tried to create a custom IInterTabClient. It works when I drag out but when i want to replace the tab in the original layout I got an other exception. (The ConsolidateOrphanedItems don't work too)

My custom IInterTabClient
```
public class InterTabClient : IInterTabClient
{
    private ISLocViewModel _viewModel;


    public ISLocInterTabClient(ISLocViewModel viewModel)
    {
        _viewModel = viewModel;
    }


    public INewTabHost<Window> GetNewHost(IInterTabClient interTabClient, object partition, TabablzControl source)
    {
        TabWindow window = new TabWindow();
        window.DataContext = _viewModel;
        return new NewTabHost<Window>(window, window.InitialTabablzControl);
    }

    public TabEmptiedResponse TabEmptiedHandler(TabablzControl tabControl, Window window)
    {
        return TabEmptiedResponse.CloseWindowOrLayoutBranch;
    }
}
```

My window dedicated to tab
```
<Window x:Class="Satroem.Views.TabWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:dragablz="clr-namespace:Dragablz;assembly=Dragablz"
        xmlns:dockablz="clr-namespace:Dragablz.Dockablz;assembly=Dragablz"
        xmlns:local="clr-namespace:Satroem.Views"
        WindowStartupLocation="CenterScreen" FontFamily="Calibri"
        Title="Satroem" Height="720" Width="1280">
    <dragablz:TabablzControl x:Name="InitialTabablzControl" BorderThickness="0" Margin="0,-1,0,1" ConsolidateOrphanedItems="True">
    </dragablz:TabablzControl>
</Window>
```

Inner exception
```
Unable to ascrtain tab control.
At Dragablz.DefaultInterLayoutClient.GetNewHost(Object partition, TabablzControl source) in DefaultInterLayoutClient.cs:line 22
At Dragablz.Dockablz.Layout.Branch(DropZoneLocation location, DragablzItem sourceDragablzItem) in Layout.cs:line 489
At Dragablz.Dockablz.Layout.ItemDragCompleted(Object sender, DragablzDragCompletedEventArgs e) in Layout.cs:line 644
```

Where is my mistake?

**Comment by ButchersBoy** [comment]
is that the full stack?

**Comment by AnthonyLHOMME** [comment]
Yes

NullReferenceException
Data : {System.Collections.ListDictionaryInternal}

**Comment by ButchersBoy** [comment]
> Object reference not set to an instance of an object.

or

> NullReferenceException

?????????????????????????????

Post a full repo as a GitHub project and I'll look when I get chance.

**Comment by ButchersBoy** [comment]
Please post a full github repository, I will look when p[ossible.

**Comment by AnthonyLHOMME** [comment]
My stacktrace is
```
System.NullReferenceException: Object reference not set to an instance of an object.\r\n   à At Dragablz.DefaultInterLayoutClient.GetNewHost(Object partition, TabablzControl source) in DefaultInterLayoutClient.cs:line 22
At Dragablz.Dockablz.Layout.Branch(DropZoneLocation location, DragablzItem sourceDragablzItem) in Layout.cs:line 489
At Dragablz.Dockablz.Layout.ItemDragCompleted(Object sender, DragablzDragCompletedEventArgs e) in Layout.cs:line 644
```

**Comment by AnthonyLHOMME** [comment]
I will do that ASAP, I can't post the full project.

**Comment by ButchersBoy** [comment]
OK...looking at that line...I suspect your new Window / Tab doesnt have it's InterTabController set...try setting that via a Style...so it is always available.  This is a good example: https://github.com/ButchersBoy/doobry

**Comment by AnthonyLHOMME** [comment]
It works ! Thanks a lot James, great project :+1:

**Comment by AnthonyLHOMME** [comment]
I reopen the issue.
I can drag out tab and replace tab in layout but when I want to place tab on side (top, left, right or bottom) of layout, I got an exception.
The InterTabController is set via style

`
System.InvalidOperationException: Specified element is already the logical child of another element. Disconnect it first.
At System.Windows.FrameworkElement.ChangeLogicalParent(DependencyObject newParent)
At System.Windows.FrameworkElement.AddLogicalChild(Object child)
At Dragablz.TabablzControl.InterTabControllerPropertyChangedCallback(DependencyObject dependencyObject, DependencyPropertyChangedEventArgs dependencyPropertyChangedEventArgs) in TabablzControl.cs:line 346
At System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
At System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
At System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
At System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
At System.Windows.StyleHelper.ApplyStyleOrTemplateValue(FrameworkObject fo, DependencyProperty dp)
At System.Windows.StyleHelper.InvalidateContainerDependents(DependencyObject container, FrugalStructList`1& exclusionContainerDependents, FrugalStructList`1& oldContainerDependents, FrugalStructList`1& newContainerDependents)
At System.Windows.StyleHelper.DoStyleInvalidations(FrameworkElement fe, FrameworkContentElement fce, Style oldStyle, Style newStyle)
At System.Windows.StyleHelper.UpdateStyleCache(FrameworkElement fe, FrameworkContentElement fce, Style oldStyle, Style newStyle, Style& styleCache)
At System.Windows.FrameworkElement.OnStyleChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
At System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
At System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
At System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
At System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
At System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
At System.Windows.FrameworkElement.UpdateStyleProperty()
At System.Windows.TreeWalkHelper.InvalidateOnTreeChange(FrameworkElement fe, FrameworkContentElement fce, DependencyObject parent, Boolean isAddOperation)
At System.Windows.FrameworkElement.OnVisualParentChanged(DependencyObject oldParent)
At System.Windows.Media.Visual.FireOnVisualParentChanged(DependencyObject oldParent)
At System.Windows.Media.Visual.AddVisualChild(Visual child)
At System.Windows.FrameworkElement.set_TemplateChild(UIElement value)
At System.Windows.Controls.ContentPresenter.UseContentTemplate.BuildVisualTree(FrameworkElement container)
At System.Windows.StyleHelper.ApplyTemplateContent(UncommonField`1 dataField, DependencyObject container, FrameworkElementFactory templateRoot, Int32 lastChildIndex, HybridDictionary childIndexFromChildID, FrameworkTemplate frameworkTemplate)
At System.Windows.FrameworkTemplate.ApplyTemplateContent(UncommonField`1 templateDataField, FrameworkElement container)
At System.Windows.FrameworkElement.ApplyTemplate()
At System.Windows.FrameworkElement.MeasureCore(Size availableSize)
At System.Windows.UIElement.Measure(Size availableSize)
At System.Windows.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
At System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
At System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV)
At System.Windows.Controls.Grid.MeasureOverride(Size constraint)
At System.Windows.FrameworkElement.MeasureCore(Size availableSize)
At System.Windows.UIElement.Measure(Size availableSize)
At System.Windows.Controls.Border.MeasureOverride(Size constraint)
At System.Windows.FrameworkElement.MeasureCore(Size availableSize)
At System.Windows.UIElement.Measure(Size availableSize)
At System.Windows.Controls.Control.MeasureOverride(Size constraint)
At System.Windows.FrameworkElement.MeasureCore(Size availableSize)
At System.Windows.UIElement.Measure(Size availableSize)
At MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
At System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
At System.Windows.FrameworkElement.MeasureCore(Size availableSize)
At System.Windows.UIElement.Measure(Size availableSize)
At System.Windows.Controls.Grid.MeasureOverride(Size constraint)
At System.Windows.FrameworkElement.MeasureCore(Size availableSize)
At System.Windows.UIElement.Measure(Size availableSize)
At System.Windows.ContextLayoutManager.UpdateLayout()
At System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
At System.Windows.Media.MediaContext.InvokeOnRenderCallback.DoWork()
At System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
At System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
At System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
At System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
At System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
`

**Comment by ButchersBoy** [comment]
Make it NOT shared.

https://github.com/ButchersBoy/doobry/blob/master/Doobry/MainWindow.xaml#L55

**Comment by AnthonyLHOMME** [comment]
When I set to not shared I got an exception when I drag out.
I post my solution at [https://github.com/AnthonyLHOMME/Dragablz_sample](url)

**Comment by AnthonyLHOMME** [comment]
any advice?

**Comment by ButchersBoy** [comment]
Yeah, when I said "make it NOT shared", and posted a link to a sample, I meant "make it NOT shared".

Your example is still shared!

```
<dragablz:InterTabController x:Key="InterTabController" x:Shared="True" InterTabClient="{Binding InterTabClient}" />
```

Also, your solution doesn't compile as there are some missing dependencies:

![image](https://cloud.githubusercontent.com/assets/658107/19677490/788fd0fe-9a91-11e6-8193-a3613629475b.png)

Please appreciate that I am trying to help, but I can't answer every question within a day or two as I (like I'm sure you are too) am very busy.

If you still can't get it to run after marking ``` x:Shared="False" ``` please add the missing dependencies and update the repo so I can get it running with minimal fuss, and post the current exception.

**Comment by AnthonyLHOMME** [comment]
I understand you can't answer me within a day, I'm thankful you try to help me.
My sample is still shared because I didn't push with NOT shared.
I update the repo with the modification.

InnerException with not shared
```
System.ApplicationException: Unable to ascrtain tab control.
At Dragablz.DefaultInterTabClient.GetNewHost(IInterTabClient interTabClient, Object partition, TabablzControl source) in DefaultInterTabClient.cs:line 21
At Dragablz.TabablzControl.MonitorBreach(DragablzDragDeltaEventArgs e) in TabablzControl.cs:line 1195
At Dragablz.TabablzControl.ItemDragDelta(Object sender, DragablzDragDeltaEventArgs e) in TabablzControl.cs:line 1112
```

**Comment by ButchersBoy** [comment]
"Unable to ascrtain tab control" _Damn I need to fix that spelling mistake_

When a window/tab tears out a new Window is immediately created.  There is one golden rule; **a new tab control must be available to continue the user's drag operation.**

It seems to me that when you new MainWindow is created the tab control is not there.  As you are using PRISM it is your app's code responsibility to get that tab control in place.

Dragablz provides hooks for you to jump in and make those preparations.  You need to provide a custom ``` IInterTabClient ``` as part of your ``` InterTabController ```.

If you do this the interface will force you to get your tab control ready, and then it should start working.

**Comment by AnthonyLHOMME** [comment]
But I don't understand I provide a custom IInterTabClient via style

**Comment by ButchersBoy** [comment]
I think the DataContext is not what you think it is...if you add those missing dependencies, and mark all Controllers as not shared I will debug it for you.

**Comment by AnthonyLHOMME** [comment]
I pushed a new version with not shared and dependancies resolved.

https://github.com/AnthonyLHOMME/Dragablz_sample

**Comment by ButchersBoy** [comment]
OK, using snoop I can delve into the InterTabController and see that the DatabContext is getting lost, and thus so is the InterTabClient:

![image](https://cloud.githubusercontent.com/assets/658107/19684292/5ba5fd0c-9aae-11e6-9189-d89413c2a929.png)

This is happening even though the InterTabClient is a logical child of TabablzControl; I'm guessing the shared resource is causing issue here.

The complexity you have is because you are using <Layout> You only need this for side-by-side layouts.  But you have various options to get up and running:

1) Remove the Layout tag and put the InterTabController directly back as a property of TabablzControl

2) Use a Layout.BranchTemplate (and again put the InterTabController directly back as a property of **two** TabablzControl instances (the default, and the template).  Again here be wary of what your data context is.  Use Snoop to help you. Example here: https://github.com/ButchersBoy/Dragablz/blob/master/DragablzDemo/BoundExampleWindow.xaml#L53

3) Use a totally static InterTabClient.  This often helps remove a lot of the complexity around DataContext.  Example: https://github.com/ButchersBoy/doobry/blob/master/Doobry/MainWindow.xaml#L55

**Comment by AnthonyLHOMME** [comment]
The use of Layout.BranchTemplate and define InterTabController directly as a property works great.
Thanks a lot for your help

**Comment by ButchersBoy** [comment]
Awesome, we got there in the end, good luck with your app!

**Comment by kushwb** [comment]
I am facing the same issue. Could you please help me out. Couldn't find the sample code at https://github.com/AnthonyLHOMME/Dragablz_sample

**Comment by ButchersBoy** [comment]
> Use a totally static InterTabClient. This often helps remove a lot of the complexity around DataContext. 

Example: https://github.com/ButchersBoy/doobry/blob/master/Doobry/MainWindow.xaml#L55

**Comment by kushwb** [comment]
Thanks for your quick response. So the only way to tear off a tab from a user control is to implement a custom InterTabClient. Isn't it ?

**Comment by ButchersBoy** [comment]
No.  You can use the default.  A custom one just gives you more intercept points.

**Comment by kushwb** [comment]
But when I use the default( TabablzControl in a User control it throws out exception when I try to take it out as its mentioned in this thread above.  I was able to make it work by implementing the IInterTabClient and creating a window for the new tabcontrol through it(as mentioned above). The default works only if it resides directly in MainWindow.

`
<UserControl>...
<dockablz:Layout>
		<dragablz:TabablzControl BorderThickness="0"
                                 Margin="0,-1,0,1" Name="MainTab" ItemsSource="{Binding TabItems}" >
					<dragablz:TabablzControl.InterTabController>
						<dragablz:InterTabController InterTabClient="{Binding InterTabClient}" />
					</dragablz:TabablzControl.InterTabController>
			<TabItem Header="DIALOGS"/>
			<TabItem Header="MAHAPPS"/>
			<TabItem Header="PALETTE"/>
		</dragablz:TabablzControl>
</dockablz:Layout>
</UserControl>`

**Comment by ButchersBoy** [comment]
You are manually specifying an InterTabClient with the Binding.   You might be using DefaultInterTabClient, I can't tell from your snippet.  But you have manually specified a binding, so on subsequent windows it is examining the binding again.  But your DataContext is different so it doesn't find it.

So, you either remove the InterTabClient and allow it to always use the default (with no binding there to override it), or you make sure your Binding works whether you are in the startup Window or in a new window.

There a different was to do this but:

> Use a totally static InterTabClient. This often helps remove a lot of the complexity around DataContext.

Example: https://github.com/ButchersBoy/doobry/blob/master/Doobry/MainWindow.xaml#L55

**Comment by kushwb** [comment]
If I use the default binding(i.e. removing InterTabClient="{Binding InterTabClient}" ) leads to an exception. 
I am new to this so pardon me if I sound confused. Were there recent changes done in dragablz nuget to handle this scenario so that to make this work with default (with no binding mentioned).

**Comment by ButchersBoy** [comment]
If you post a GitHub repo I will try and take a look.  No zip files please.
