### ISSUE TITLE
FixedHeaderCount with TabStripPlacement="Left" has no effect

### ISSUE THREAD

**Issue by YTsalko** [ButchersBoy/Dragablz#128]
When using FixedHeaderCount with TabStripPlacement="Left", I expect tabs dragging will be disabled (the same as when you use FixedHeaderCount with default  TabablzControl). Unfortunately, tabs still could be rearranged.

Is it a bug or I'm doing something wrong?

Markup to reproduce:

```xaml
<dragablz:TabablzControl
            TabStripPlacement="Left"
            FixedHeaderCount="4">
...
</dragablz:TabablzControl>
```

**Comment by ButchersBoy** [comment]
You're using the Material theme?

**Comment by YTsalko** [comment]
Yes, I am.
