### ISSUE TITLE
Application quit when closing all TabItem

### ISSUE THREAD

**Issue by kogare** [ButchersBoy/Dragablz#13]
Current behavior is to quit the application when closing all TabItem, because this control must be able to close current parent window on multiple window when using tearable option. 

But its when there is only one window, its kinda weird, closing all TabItem = closing application. 
Should we put multiple window validation before calling window.Closes()?

Cheers

**Comment by ButchersBoy** [comment]
There is already a hook provided so you can suppress this behaviour.  You need to implement your own [IInterTabClient](https://github.com/ButchersBoy/Dragablz/blob/master/Dragablz/IInterTabClient.cs) and provide it via the InterTabController.  

Something like:

```
<TabablzControl>
    <TabablzControl.InterTabController>
        <InterTabController InterTabClient="{Binding MyInterTabClient}">
```

By default, the [DefaultInterTabClient](https://github.com/ButchersBoy/Dragablz/blob/master/Dragablz/DefaultInterTabClient.cs) client is used.

You can create your own, **however** to make things a little easier I have made the members on DefaultInterTabClient virtual (NuGet .102) so you can derive from that class if you want.

In your case, when you are programmatically removing items, you might need to temporarily adjust the **TabEmptiedResponse**, which will worked, as it is checked every-time.  You may also be interested in IsClosingAsPartOfDragOperation which can help you distinguish when TabablzControl is closing the tab.

Hope this helps, gonna close this one.

**Comment by kogare** [comment]
Hi,
I add counter to count window it won't create multiple window with empty TabItem with this

            if (Application.Current.Windows.Count > 1)
            {
                return TabEmptiedResponse.CloseWindowOrLayoutBranch;
            }
            else
            {
                return TabEmptiedResponse.DoNothing;
            }

Thanks for the help

**Comment by ButchersBoy** [comment]
Hi Kogare, not quite sure what you're asking?

**Comment by kogare** [comment]
I'm add that snippet in my override codes in TabEmptiedResponse TabEmptiedHandler(TabablzControl tabControl, Window window).
Because without that statement, when I tear TabItem and then close it, the window stay open unless I close the window explicitly. It becomes a problem when I tearing several TabItems and closing them, it makes multiple windows without any TabItem, so I add that code to tell apps to close the windows if there is more than one windows.

**Comment by ButchersBoy** [comment]
ahhh, so you are happy, & everything's working?  I wasn't sure if you were asking a further question.  :)

As an aside, you might want to keep an eye on [issue #15](https://github.com/ButchersBoy/Dragablz/issues/15), as to help with that I might add another hook to help consolidate tabs.
