### ISSUE TITLE
dpi issue when resizing DragablzWindow

### ISSUE THREAD

**Issue by dptr** [ButchersBoy/Dragablz#130]
in this function : DragablzWindow::WindowResizeThumbOnDragDelta， it calculate the window's width and height by the offset of the mouse point. However, the mouse point coordinate is device-dependent pixel, and the Window's Width and Height attribute needs device-independent unit.  So when the font size of global display setting is changed (in another word, system dpi setting is changed), when resizing DragablzWindow, the width and height will not changed correctly. 

(if you are using Windows 10, try to change the global font size by right click desktop empty space -> Display settings -> change the text size to 125% or more, then resize the DragablzWindow, and this issue will be reproduced.)

**Comment by dptr** [comment]
solution:
` Matrix m = PresentationSource.FromVisual(Application.Current.MainWindow).CompositionTarget.TransformToDevice;
            xScale = m.M11;
            yScale = m.M22;`

diff /= xScale; or diff /= yScale; (depend on resizeType)

**Comment by ButchersBoy** [comment]
Hi @dptr ...can you raise a PR for this?
