### ISSUE TITLE
[Request] Add a threshold distance before dragging

### ISSUE THREAD

**Issue by askmoller** [ButchersBoy/Dragablz#133]
Add a threshold distance that the mouse-cursor must move before initiating a drag/movement/reorder of tabs.

The unselected tabs should also wait with fading before the threshold is reached.

**Comment by Arvidas** [comment]
It's not solved, not like that.
I do not see the use of SystemParameters.MinimumVerticalDragDistance and SystemParameters.MinimumHorizontalDragDistance anywhere in code. 
Do you need help?
