### ISSUE TITLE
Issue with multiple screens

### ISSUE THREAD

**Issue by Shifty15** [ButchersBoy/Dragablz#140]
Hi,
I have problem when I'm using two monitors and application is running on second monitor. When window is maximize and I drag tab and move new window start in main monitor not in secondary. I saw same issue #95 but i think that problem is not solved.
Thank you

**Comment by ButchersBoy** [comment]
My second monitor has just packed up and died  :/

What type of Window are you using?

**Comment by Shifty15** [comment]
I'm using mahApss metro window. And I downloaded project from here and I have same problem.

**Comment by ButchersBoy** [comment]
I'm afraid I can't look at it right now as I'm a monitor down...
