### ISSUE TITLE
Feature Request: Close Window -> Rearrange back to Tab

### ISSUE THREAD

**Issue by jogibear9988** [ButchersBoy/Dragablz#15]
Would It be possible to include a Property, that Tabs could not be closed? When this is set, and a Window with Tabs is closed, the Tabs are arranged back to the main TabControl!

**Comment by ButchersBoy** [comment]
Hi,

My initial reaction to this was "that's some kind of specialised behaviour that should be managed with the app", but after thinking this through, I can see the case for it, especially if you have ```TabablzControl.ShowDefaultCloseButton``` turned off, which is the default starting position.

I'll have a little think about how to implement it.  In the mean-time, there are enough hooks for you to do this yourself in some kind of tab contoller/window manager type set-up.

I'll draw your attention to a few hooks:

If ```TabablzControl.ShowDefaultCloseButton``` is turned off and you want to allow only specific tabs to be close-able, you can implement a custom header (MVVM based) which contains a button using '''TabablzControl.CloseItemCommand'''.  See [CustomHeader.xaml example](https://github.com/ButchersBoy/Dragablz/blob/master/DragablzDemo/CustomHeader.xaml).

You would need a hook onto your windows.  You can intercept Dragablz creation of new windows by implementing ```IInterTabClient```, and setting this property on the ```InterTabController```.  There is a [```DefaultInterTabClient```](https://github.com/ButchersBoy/Dragablz/blob/master/Dragablz/DefaultInterTabClient.cs) which you can look at to get started.  Also see this [blog post](http://dragablz.net/2014/11/18/getting-started-with-dragablz-tabablzcontrol/).

Finally, you can check if a window is closing as part of a drag operation by inspecting the attached property ```TabablzControl.GetIsClosingAsPartOfDragOperation(Window)```.  So, if this returns false inside a ```Window.Closing``` event you could consider it a user driven close, pull the tabs, find another Window, and add them into that tab control.

**Comment by ButchersBoy** [comment]
OK, implemented a new property and a new (optional) hook.  ```TabablzControl.ConsolidateOrphanedItems``` is your new friend.  Setting this will cause tab items to  move to another tab/window if a window is closed.

One caveat, is they appear next to the currently selected tab in the target window, and not on the end.  But I have another issue open for this so when I look at that it should get resolved.

I've also provided ```ConsolidatingOrphanedItemCallback```.  This will allow you to cancel the tab consolidation on a per tab basis.  This would be useful have a you have some mandatory/fixed tabs, and some additional tabs that the user might open on demand.

I'll leave this issue open for a bit; let me know how you get on.

NuGet build 0.0.1.103.

**Comment by jogibear9988** [comment]
yes, I've seen, but I don't yet had time to test!
but thank you!!
