### ISSUE TITLE
Question: Hide Tab Headers

### ISSUE THREAD

**Issue by RickStrahl** [ButchersBoy/Dragablz#160]
Is there a way to hide the tab headers so that the just the content of the tabs displays?

Trying to implement a distraction free mode and for that want to hide tab headers, but can't seem to get anything to work to have the headers not show.

This has no effect:

```cs                        
foreach(TabItem tab in Window.TabControl.Items)
                            tab.Visibility = Visibility.Collapsed;
```

**Comment by ButchersBoy** [comment]
Yeah...I think i can do that... Will have to add a new property.

**Comment by RickStrahl** [comment]
My workaround for this was use a custom template and bind it to configuration setting. 

```xml
<Style x:Key="TrapezoidDragableTabItemStyle"  TargetType="{x:Type local:DragablzItem}">
<Setter Property="Visibility" 
 Value="{Binding RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type mm:MainWindow}}, 
 Path=Model.Configuration.WindowPosition.TabHeadersVisible}" />
```       

Less than ideal for sure, but in this case where I am already using custom templates, this does the trick.

A property specifically to hide headers or to hide a header on a tab would be cleaner for sure.

**Comment by ButchersBoy** [comment]
Yeah, leave this issue open...got a spend a couple of days catching up on Dragablz stuff soon.

**Comment by RickStrahl** [comment]
So I'm back to this. It looks like you can do something like this in a custom style:

```xml
<Style x:Key="TrapezoidDragableTabItemStyle"  TargetType="{x:Type local:DragablzItem}">
        <Setter Property="Visibility" Value="Collapsed" />
```

That works (but obviously not so useful :-). How can I get at the actual tab control I'm using? Looking at the live visual tree I don't even see the MetroTabItem anywhere:

```xml

<controls:MetroTabItem Name="TabTopicLinks" Header="Topic Links" Margin="0,0,5,0" CloseButtonEnabled="False"                                   
                        controls:ControlsHelper.HeaderFontSize="16"  Visibility="Collapsed"  >
    <Grid>
    </Grid>
</controls:MetroTabItem>
```

How can I reference this MetroTabItem (or TabItem) from within the style?

**Comment by ButchersBoy** [comment]
The TabItem never actually gets used in the visual tree, only a DragablzItem.  So with the default styles, DragablzItem instances are styled to look like tabs (I guess you already figured this out).  Apart from an easier why to hide the tabs, what else are you actually looking to do?

**Comment by ButchersBoy** [comment]
new: ```IsHeaderPanelVisible```

**Comment by RickStrahl** [comment]
Nice. Thank you. That solves one of a frequent note I get from users in Markdown Monster who use distractionfree mode.

**Comment by RickStrahl** [comment]
Checked it out in MM and it works great to hide the full tab header panel. Sweet!

**Comment by ButchersBoy** [comment]
Cool! Sorry it took so long!

**Comment by coderUT** [comment]
I'm finding that if you set "IsHeaderPanelVisible" to false, then the underlying DragablzItemsControl reports that there are no DragablzItems (even if there are open tabs). The Containers enumerable in DragablzItemsControl returns empty when it shouldn't. I'm guessing this has something to do with the fact the way that IsHeaderPanelVisible modifies the visual tree. Is this expected behavior?
