### ISSUE TITLE
Unable to drop if TabablzControl is in DataTemplate

### ISSUE THREAD

**Issue by codebude** [ButchersBoy/Dragablz#162]
I'm using Dragablz in combination with MahApps and [MahApps.HamburgerMenu](http://jkarger.de/2017/02/06/mahapps-hamburgermenu/). Therefore I moved the TabablzControl to the DataTemplate of the HamburgerMenu. But when doing so, I can't drop the Tabs, because of an "_Unable to ascertain tab control._" error. What am I doing wrong?

Code: https://pastebin.com/sTq5Y7nN

**Comment by ButchersBoy** [comment]
Hi, could you please post a GitHub repo.  I am quite often behind a mean proxy.

**Comment by codebude** [comment]
I uploaded the code here: https://github.com/codebude/DragablzHamburgerMenu

**Comment by codebude** [comment]
@ButchersBoy - issue can be closed. I moved the DragablzControl from MahApp's HamburgerMenu.ContentTemplate to the Content property. So the Dragablz-object is accessible and I can use the standard IntertabController/Client. 

(For others, who have the same problem - there is an Bug in the current MahApps version - update to the latest Alpha (currently 1.5.0) and the Content-property workaround will work.)
