### ISSUE TITLE
ClosingTabItemHeader Asynchronously

### ISSUE THREAD

**Issue by HamedMousavi** [ButchersBoy/Dragablz#166]
Attempting to implement a "Save unsaved changes to the tab content?" upon closing:

A solution would be to show a modal dialog using DialogHost in MaterialDesign asking user to confirm closing the form. However, if user decides to save changes before closing, I need to "Cancel()" current tabs' close process. (because content of the tab control is a data entry form that might have invalid data in which case user will need to fix errors thus the need to keep the tab we just prevented closing.)

The problem is that the tab control only supports synchronous close cancellation (calling Cancel in an async event handler didn't work) while Material Design DialogHost.Show only supports async call. I decided to always cancel close and call close via code again if all conditions are met but the I couldn't find any methods to manually close a tab item from within the closing event. Although, provided examples show how to use a Close command so one way might be to find the command and invoke it but it probably would be too complex and the outcome of calling close from within the event would be unknown.

Anyway, I will use a custom "sync" modal dialog to handle this scenario but I believe this needs a little more thought and perhaps coordination with the MaterialDesign modal dialog system.

Tanks for the project, BTW. Very useful and well implemented. :-)

**Comment by ButchersBoy** [comment]
It might be better to close the item by finding it and removing it from your source collections (which source collection depends on if you are using MVVM, Layout splitting etc).

**Comment by HamedMousavi** [comment]
Good idea, thank you, I will try finding the bound item and removing it.

**Comment by ButchersBoy** [comment]
``` TabablzControl.RemoveFromSource() ``` might help a bit.

**Comment by HamedMousavi** [comment]
Thank you. Removing an item from the view model worked. :-)

It's nice to know the alternative though.
