### ISSUE TITLE
Refreshing content in tab

### ISSUE THREAD

**Issue by SoulXHades** [ButchersBoy/Dragablz#167]
Hi. Currently I have a table grid in one of the tabs. However, I am unable to refresh the table after new row(s) are added to it through another tab. Before that, I called Load method to refresh the list in windows. Since tab control is unable to load the Load method, I set the ItemsSource in the constructor of the c# file instead. Is there a way to let it refresh without closing it and opening a new tab?

**Comment by ButchersBoy** [comment]
You need to post some sample code and markup.

Standard WPF rules apply.  INotifyPropertChanged or ObservableCollections etc

**Comment by SoulXHades** [comment]
I'm so sorry. These are some of my codes.

Class to display data:
public partial class CaseGrid : UserControl
    {
        public CaseGrid()
        {
            InitializeComponent();
        }

        private void CaseGrid1_Loaded(object sender, RoutedEventArgs e)
        {
            using (var context = HCEntities.Create())
            {
                var query2 =
                from OrderTable in context.OrderTables
                orderby OrderTable.OrderID_O
                orderby OrderTable.OrderDate_O
                orderby OrderTable.CustomerName_O
                orderby OrderTable.DeliveryAddress_O

                select new { OrderId = OrderTable.OrderID_O, Date = OrderTable.OrderDate_O, CustomerName = OrderTable.CustomerName_O, DeliveryAddress = OrderTable.DeliveryAddress_O.Replace(Environment.NewLine, " ") };

                var query2sorted = query2.OrderBy(n => n).ToList();
                CaseGrid1.ItemsSource = query2sorted;
            }
        }
    }

--------------------------------------------------------------------------------
From Mainwindow that add tabs when certain buttons are click:
MainWindowTabs MWTexist = new MainWindowTabs();

private void casegrid_Click(object sender, RoutedEventArgs e)
        {
            CaseGrid casegrid = new CaseGrid();
            TabItem CaseTabItem = new TabItem()
            {
                Header = "CaseGrid",
                Name = "CaseGridTab",
                Content = casegrid
            };

                MWTexist.CaseGridTabExist = false;
                var headers = DragablzTC.Items.Cast<TabItem>().Select(x => x.Header).ToList();
                string[] headersarray = headers.Select(i => i.ToString()).ToArray();            //contains arrays of headers current exist
                foreach (string i in headersarray)
                {
                    if (i == "CaseGrid")
                    {
                        MWTexist.CaseGridTabExist = true;
                    }
                }

                if (MWTexist.CaseGridTabExist == false)
                {
                    DragablzTC.AddToSource(CaseTabItem);
                    TabablzControl.SelectItem(CaseTabItem);
                }
        }

        private void casecreation_Click(object sender, RoutedEventArgs e)
        {
            CaseCreation casecreation = new CaseCreation();
            TabItem CaseCreationTabItem = new TabItem()
            {
                Header = "CaseCreation",
                Name = "CaseCreationTab",
                Content = casecreation
            };
                MWTexist.CaseCreationTabExist = false;
                var headers = DragablzTC.Items.Cast<TabItem>().Select(x => x.Header).ToList();
                string[] headersarray = headers.Select(i => i.ToString()).ToArray();            //contains arrays of headers current exist
                foreach (string i in headersarray)
                {
                    if(i == "CaseCreation")
                    {
                        MWTexist.CaseCreationTabExist = true;
                    }
                }

                if (MWTexist.CaseCreationTabExist == false)
                {
                    DragablzTC.AddToSource(CaseCreationTabItem);
                    TabablzControl.SelectItem(CaseCreationTabItem);
                }
        }

--------------------------------------------------------------------------------
Properties:
internal class MainWindowTabs
    {
        internal bool CaseGridTabExist { get; set; }
        internal bool CaseCreationTabExist { get; set; }
    }

--------------------------------------------------------------------------------
From a class that allows user to key in infomation:
public partial class CaseCreation
{
private void SaveButton_Click(object sender, RoutedEventArgs e)
        {
            using (var context = HCEntities.Create())
	    {
		 OrderTable CCT = new OrderTable { OrderID_O = OrderIDO.Text, OrderDate_O = OrderDateO, CustomerName_O = OrderCustomerLists.Text, DeliveryAddress_O = CustOrderDeliveryAddress.Text };
                 context.OrderTables.Add(CCT);
                 context.SaveChanges();
	    }
        } 
}

Since the data is extracted from entity framework, I don't think it is possible to use Inotifypropertychanged in CaseGrid class unless it can be called from the CaseCreation class.

**Comment by SoulXHades** [comment]
It's okay. I found a way to do it. Thank you.

**Comment by CK-DBH** [comment]
> It's okay. I found a way to do it. Thank you.

Hi Soul Hades, 
I have that same problem. What was the solution you found?

**Comment by ucarkadir** [comment]
> > It's okay. I found a way to do it. Thank you.
> 
> Hi Soul Hades,
> I have that same problem. What was the solution you found?

Hi, 
I have been still searching solution, how you could done it.
Thanks for your reply
