### ISSUE TITLE
Simple way to override AddButton?

### ISSUE THREAD

**Issue by BornToBeRoot** [ButchersBoy/Dragablz#179]
Is there a simple way to override the add button for creating new tabs?

I want a custom icon like:

![image](https://user-images.githubusercontent.com/16019165/31400001-66008b4c-adee-11e7-9743-0951f798d8bd.png)

**Comment by ButchersBoy** [comment]
You don't have to use ```.ShowDefaultAddButton```.  You can use ```.HeaderSuffixContent``` to add your own content, which could be your button, and _could_ use the stabdard routed command (or bind to one of your view models etc).

```
<Button Style="{StaticResource YourCustomStyle}"
              Command="{x:Static local:TabablzControl.AddItemCommand}">
    . . .
</Button>
```

**Comment by BornToBeRoot** [comment]
Thanks!! 

![image](https://user-images.githubusercontent.com/16019165/31469942-13116356-aee4-11e7-9715-c276054620ac.png)

Btw: Great work 👍
