### ISSUE TITLE
Disallow/Disable Drag & Drop/Drag Out

### ISSUE THREAD

**Issue by RoachxD** [ButchersBoy/Dragablz#18]
In my opinion these options would make the "Assembly" more customizable overall.

# **Disallow Drag & Drop**
## _**Whole Control**_
```XAML
<dragablz:TabablzControl DissalowDragDrop="True">
    <dragablz:TabablzControl.InterTabController>
        <dragablz:InterTabController/>
    </dragablz:TabablzControl.InterTabController>

    <TabItem Header="Tab 1" />
    <TabItem Header="Tab 2" />
    <TabItem Header="Tab 3" />
</dragablz:TabablzControl>
```
## _**Single Tabs**_
```XAML
<dragablz:TabablzControl>
    <dragablz:TabablzControl.InterTabController>
        <dragablz:InterTabController/>
    </dragablz:TabablzControl.InterTabController>

    <TabItem Header="Tab 1" DissalowDragDrop="True" />
    <TabItem Header="Tab 2" DissalowDragDrop="True" />
    <TabItem Header="Tab 3" DissalowDragDrop="True" />
</dragablz:TabablzControl>
```
# **Disallow Drag Out**
## _**Whole Control**_
```XAML
<dragablz:TabablzControl DissalowDragOut="True">
    <dragablz:TabablzControl.InterTabController>
        <dragablz:InterTabController/>
    </dragablz:TabablzControl.InterTabController>

    <TabItem Header="Tab 1" />
    <TabItem Header="Tab 2" />
    <TabItem Header="Tab 3" />
</dragablz:TabablzControl>
```
## _**Single Tabs**_
```XAML
<dragablz:TabablzControl>
    <dragablz:TabablzControl.InterTabController>
        <dragablz:InterTabController/>
    </dragablz:TabablzControl.InterTabController>

    <TabItem Header="Tab 1" DissalowDragOut="True" />
    <TabItem Header="Tab 2" DissalowDragOut="True" />
    <TabItem Header="Tab 3" DissalowDragOut="True" />
</dragablz:TabablzControl>
```

**Comment by ButchersBoy** [comment]
Hey.  Firstly you can achieve some of these options with the existing API:

* To disable the tear-out for a whole tab simply remove the InterTabController.
* Look at the InterTabController.Partition property.  Using this, you can create siloed TabControls that will not interact with each other:

```
<dragablz:TabablzControl>
    <dragablz:TabablzControl.InterTabController>
        <dragablz:InterTabController Partition="Primary" />
    </dragablz:TabablzControl.InterTabController>        
</dragablz:TabablzControl>
```

So that leaves us with the final option of making indivudual tabs that cannot tear out.  To be honest, I see limited use case for this...unless - say - the "pinned" tabs were fixed to the start of the tab list; but I will look into getting fixed tabs added.

James

**Comment by RoachxD** [comment]
Yeah, I was about to write to you about the tear-out for a whole tab, that it was enough to remove the InterTabController, I just saw that (I know, I really think I need a pair of glasses).

Anyways, thanks for getting individual fixed tabs implemented, that would be really helpful.

Have a nice day, James!

**Comment by ButchersBoy** [comment]
Added a FrozenHeaderCount property.  Think all this stuff is covered now.

**Comment by josh2112** [comment]
Take note, 5 years later and the property is now FixedHeaderCount!  Hopefully that saves someone some time.
