### ISSUE TITLE
Vertical Tab Control - No Animation

### ISSUE THREAD

**Issue by RoachxD** [ButchersBoy/Dragablz#19]
I just realized that there's no Animation on the Vertical Tab Control (Using Material Design one).

I mean the OnClick Animation.

**Comment by ButchersBoy** [comment]
ahhh...OK.

**Comment by RoachxD** [comment]
Announce me when it's fixed.

Thanks in advance!

Adrian

**Comment by ButchersBoy** [comment]
Fixed.  Also bought the animations more in-line with the rest of Material Design in XAML Toolkit.
