### ISSUE TITLE
Crashes with .NET 4.61: Could not load type 'System.Windows.DpiScale' in PresentationCore

### ISSUE THREAD

**Issue by RickStrahl** [ButchersBoy/Dragablz#204]
With the latest of Dragablz version (0.0.3.203) I'm seeing failures in a deployed application when users are running pre-4.62 versions of .NET. 

This is inside [Markdown Monster](https://markdownmonster.west-wind.com) and I'm seeing a lot of these errors in my analytics logs:

![image](https://user-images.githubusercontent.com/1374013/40703797-38b8b8d6-639b-11e8-8bbc-f57c34ca7ff5.png)

This started after installing the latest version of Dragablz  - none before the update.

MM is compiled against .NET 4.62 (need the new DPI Scaling features) but we bump down the supported runtime all the way to 4.52 to allow older versions of .NET to work (more info on why [here](https://weblog.west-wind.com/posts/2017/Jan/09/Faking-out-the-NET-Runtime-Version)). This has been working great without issues up to now.

So my question is - any idea what's changed that might be causing this issue and is there anything I can do about it?

**Comment by punker76** [comment]
@RickStrahl this is more an issue for [ControlzEx](https://github.com/ControlzEx/ControlzEx). But this should be only working with the .Net 4.6.2, so I'm a little bit confused to see this at 4.6.1

**Comment by punker76** [comment]
@RickStrahl So my questions is, after I've read your article, is this the problem? https://github.com/ControlzEx/ControlzEx/blob/2a937e3e841cb0087cfdbb8f3b4caea7f781dd1b/src/ControlzEx/Microsoft.Windows.Shell/Standard/DpiHelper.cs#L116-L120
You use ControlzEx, compiled against .Net 4.6.2, but after faking to 4.5.2, this call will be still used and crashed now, cause the real installed version is pre 4.6.1...?

**Comment by punker76** [comment]
@RickStrahl or is the problem maybe, that we onyl have .net4 .net4.5 and .net 4.6.2 and no .net4.6 target... mh this could be the real thing.
/cc @batzen

**Comment by RickStrahl** [comment]
Let me close this here, since this is the wrong forum for this question. I really shouldn't post issues at 1am in the morning :-)
