### ISSUE TITLE
Keeping the tabs order synced with a bound ItemsSource like ObservableCollection

### ISSUE THREAD

**Issue by Damian-P** [ButchersBoy/Dragablz#22]
Hello,
First of all I want to say that it's a great project and thank you for that awesome work.

Today if I add a view, it's placed at the second position in the control no matter the way it's added (insert or add) to the list if the desired index in greater than 0.

I'm binding the itemsSource of the TabablzControl to an ObservableCollection of views and I want my tabs to be synchronized with that ObservableCollection.
For example if I add a view to the bound list, I would like it to be at the end in the control. Also if I move a tab in the control I would like to reflect that on the bound list.
Maybe it is currently possible but I don't found the way to achieve that.

**Comment by ButchersBoy** [comment]
Hi Damian...quick question before I answer further, I you looking to persist a "layout" in between process life-times? i.e restore Windows tabs to their layouts from a previous session, or is this just during a single run of your app?

**Comment by ButchersBoy** [comment]
And also, have you implemented your own IInterTabClient or IManualInterTabClient?

**Comment by Damian-P** [comment]
Yes I'm looking to persist a layout. Users can create multiple workspaces. Each workspace is made of different views (some are different instances of the same class and other are uniques).
And yes I implemented the IInterTabClient.

**Comment by ButchersBoy** [comment]
Restoration of layout is the last piece of the jigsaw.  I've had plenty of experience of building a layout system in a line of business app which uses a system which is a kind of pre-cursor to Dragablz.  In that system everything was full MVVM, but it means a lot of complicated code needs to be written by the consumer, especially where the docking/nesting/MDI stuff is used.  So in Dragablz, moving items around in the ```ObservableCollection``` may not be the best way - however, you will be able to hook in to do this:

I prefer to have the controls manage the state, and then you can monitor or query the state.  But I am trying to provide hooks for this to suit varying requirements.

My preferred patter is for Dragablz to provide and API so you can query the state.  And another API so you can reconstruct the state piece by piece.  My recommendation will be for client apps to persist a set of instructions which can be used to restore the layout.  This is much more robust than for example providing a large brittle blob for example.

So far we have a Query API which can be seen in the demo apps:

![image](https://cloud.githubusercontent.com/assets/658107/7533387/ea0df5d2-f568-11e4-9c11-04925dbbae03.png)

Also, on the ```DragablzItemsControl``` you can bind in a ```PositionMonitor```, for real time monitoring of the position.  In here you could potentially update your ```ObservableCollection```.  But: 
* I need to push this up to ```TabablzControl``` 
* It is up to you to interpret this as the position can also report on X/Y dimensions, for example to the tool windows/MDI

So, to query the state we are 90% there.

To reconstruct the state is a big outstanding part; I will be starting development on this soon.  I will knock up another demo app that shows full state deconstruction/reconstruction and I am working on the API.

To clarify, as for new tabs appearing 2nd, I will see what I can do to give you control over this.  It's not quite straight forward as we cannot guarantee that every user will have their source collection matching the order of the tabs.

Glad you are enjoying Dragablz...watch this space for updates on this!

James

**Comment by ButchersBoy** [comment]
Sorry for slowness on this.  Hopefully got something coming in the next few days to help with this scenario.

**Comment by ButchersBoy** [comment]
OK, so, as I said, policy is _not_ to keep the tab headers in sync with the order of the source collection.  Been down that road in the past and decided against it.  But there are some new helper methods and properties to help you when adding stuff.  (For querying existing stuff see my comments above re. the Query API.)  

New property:
```
TabablzControl.AddLocationHint
```
This will specify where, in relation to the selected item, the item should be added.  You can add to the start/end of the tabs, or before/after the currently selected item. This hint will be used if you are using the ```AddNewItemCommand```, ```ShowDefaultAddButton```, or add to your source collection in your view model.

New (static) helper methods:
```
TabablzControl.AddItem(object item, object nearItem, AddLocationHint addLocationHint)
```
This will find the window/tab that owns the ```nearItem``` object and add to the ```Items``` or ```ItemsSource``` for that control.  If you are using the ```IManualInterTabClient``` it will defer to that to allow you to add into your collection manually.

If it helps, this technique is what I prefer and am using in a project I am currently working on.

_Still outstanding:_

Programmatic splitting of layouts.  Once this is done one should be able to reconstitute some kind of persisted layout entirely in code.

**Comment by ButchersBoy** [comment]
Layout split API is now in place, closing issue.
