### ISSUE TITLE
Add a "FrozenTabCount"

### ISSUE THREAD

**Issue by ButchersBoy** [ButchersBoy/Dragablz#23]
A lot of people seem to want to have a fixed home/start/initial tab as the first tab.  A FrozenTabCount, bit like a frozen header in Excel should be a nice way to deal with this.  Can't freeze individual tabs as dragging experience would be odd (although you can freeze *all* tabs).  Freezing from the start is do-able though.

**Comment by ButchersBoy** [comment]
Final prop name: ForzenHeaderCount.

**Comment by robertwharvey** [comment]
The actual property name is "FixedHeaderCount".  Example usage:

        <dragablz:TabablzControl BorderThickness="0" Margin="0,-1,0,1" FixedHeaderCount="7">
