### ISSUE TITLE
Adding buttons outside the control deletes the TabablzControl

### ISSUE THREAD

**Issue by itechy21** [ButchersBoy/Dragablz#24]
Is there any reason as to why? Im new to WPF and prefered WinForms but wanna give this a shot...

**Comment by ButchersBoy** [comment]
Hi, can you provide more explanation of what you are doing? Xaml/code?

**Comment by itechy21** [comment]
Using the designer and adding the button underneath the dragablz deletes it. I think it may be related to visual studio 2013...

**Comment by ButchersBoy** [comment]
Think this was just down to IDE usage.
