### ISSUE TITLE
Infinite number of windows are created when catel window is used

### ISSUE THREAD

**Issue by JanTkacik** [ButchersBoy/Dragablz#25]
Hi, 

I tried to use dragablz with catel window. I changed BoundExampleWindow to use Catel:Window instead of DragablzWindow. Now when I try to drag out the window to create new window, new windows are created until I kill the application. With standard window it works correctly.

Jan

![image](https://cloud.githubusercontent.com/assets/5746389/8157072/ea897606-1351-11e5-9db2-e26ad1ca0837.png)

**Comment by ButchersBoy** [comment]
Hi.  Haven't used Catel before, I'll try and fire up this week and have a look.

**Comment by ButchersBoy** [comment]
Had a quick look...there seems to be a few hoops I've got to jump through (view model resolution etc), and I don't really have the time to be learning Catel right now.  

Can you provide your demo project which I can fire up and see the issue straight away?

**Comment by JanTkacik** [comment]
OK, I will try to make demo project demonstrating the issue. Where should I commit it ?

**Comment by ButchersBoy** [comment]
Either create a repo under your account or email me a zip (address on my git hub home page).  A repo would be better so we can discuss any tweaks...

**Comment by ButchersBoy** [comment]
Closing and tidying due to inactivity.  Please feel free to reopen if you have a demo app to reproduce.
