### ISSUE TITLE
Drop tabs on an empty tabcontrol

### ISSUE THREAD

**Issue by l1pton17** [ButchersBoy/Dragablz#27]
Hello.
I have an application that contains not only tabcontrol, so i've overrided behaviour, that main window stay alive but child windows close.
So there was a situation, when i need to drop a tab item on the tabcontrol in mainwindow which is empty, and i couldn't do it.
Could you please add this behaviour?

**Comment by ButchersBoy** [comment]
I'll take a look...in the meantime my suggested workaround is to set FixedHeaderCount to 1 when there is a single tab left, to stop it being removed.

**Comment by ButchersBoy** [comment]
Made some changes.  If the Window stays open, a space will be left, the size of the last tab header to leave.  This will allow tabs to be dragged back in.  

I've added a new project to https://github.com/ButchersBoy/DragablzSamplez called "KeepWindowOpen"

This illustrates how a MAIN window can drag into a SUB window, but the MAIN window will always stay open and leave a target space.
