### ISSUE TITLE
Tab headers not automatically resized

### ISSUE THREAD

**Issue by jggrant** [ButchersBoy/Dragablz#28]
Steps to reproduce:
1. Open Dragablz.sln solution.
2. Open CustomHeaderViewModel.cs
3. Add the following code at the bottom of the setter of the IsSelected property.
```csharp
Header = value ? "ABCDEFGHIJKLMNOPQRSTUVWXYZ" : "123";
```
4. Build and run demo project.
5. In the "Simple form of bound tabs", click on the header with the checkbox.
6. The tab headers are no longer properly organised. Initiating a drag operation eventually brings it back to normal.

Thanks!

**Comment by ButchersBoy** [comment]
Good spot :)

**Comment by ButchersBoy** [comment]
Fixed.
