### ISSUE TITLE
When binding ItemsSource to collection of TabItems selection between tabs does not update the Selected Content

### ISSUE THREAD

**Issue by ksenkevich** [ButchersBoy/Dragablz#32]
If you bind the Tabablz control to a collection of TabItems when selecting a new tab the tab header appears to be selected, but the content does not update to the content for the newly selected tab.

**Comment by ksenkevich** [comment]
Here is a demo application to see this issue in action: https://github.com/ksenkevich/DragablzExample

**Comment by ButchersBoy** [comment]
Fixed, thanks for the feedback...and the test app...made it easy.

James
