### ISSUE TITLE
Default Add Button requires scrolling to right when many tabs open

### ISSUE THREAD

**Issue by rapat** [ButchersBoy/Dragablz#35]
Default Add Button shows up to the right of the last tab.  If there are more tabs than the control width, then left/right scroll buttons show up. 
Would be nice if the Add Button remained on screen at all times (just to the left of the scroll button if scroll buttons are visible)

**Comment by ButchersBoy** [comment]
OK...that was working...something must have regressed.

**Comment by ButchersBoy** [comment]
Which style are you using?

**Comment by rapat** [comment]
I last downloaded the code a couple months ago and then just read thru the
comments, so if its working then I just need to redownload the code.

Thanks, this is an awesome library

**Comment by rapat** [comment]
TrapezoidDragableTabItemStyle

**Comment by rapat** [comment]
downloaded latest source and looks like this is a bigger problem now -- the
add button cant be reached when the scroll buttons are visible

**Comment by ButchersBoy** [comment]
OK...will try and have a look over the next few days.

**Comment by ButchersBoy** [comment]
OK, try in the latest build, the scroll buttons should be back, and the add button should stay in view.  The scroll buttons pick up the default style; I will try and improve these in the future.
