### ISSUE TITLE
Error on adding new tab from new Window

### ISSUE THREAD

**Issue by saugat** [ButchersBoy/Dragablz#37]
I tried running the "DragablzSamplez-master" demo. It works great until add new tab button is clicked on newly created window. "Add New" button only works in default window and if it is executed from new window it throws "An unhandled exception of type 'System.InvalidOperationException' occurred in Dragablz.dll".

**Comment by ButchersBoy** [comment]
Thanks, fixed the demos, they needed to ensure the NewItemFactory property is always set.
