### ISSUE TITLE
Multi-Process Tab

### ISSUE THREAD

**Issue by saugat** [ButchersBoy/Dragablz#38]
Is it possible to create a multiple process for multiple tab like google chrome. I have tested your system and it is handling all tabs using single process. Will it be possible to do multi-process for each tab that is created dynamically.

**Comment by ButchersBoy** [comment]
The control does not directly support that.  You might want to start reading some of the threads listed on here: http://stackoverflow.com/questions/6832217/is-it-possible-to-isolate-some-controls-in-a-separate-process-in-wpf
