### ISSUE TITLE
Allow user to specify docking position

### ISSUE THREAD

**Issue by kjeremy** [ButchersBoy/Dragablz#41]
I cannot find a way to programmatically specify the docking position of a tab.  I can dock tabs by drag and drop but I'm looking for something equivalent to the `DockPanel.Dock` attached property that I can set on the `TabItem`.

**Comment by ButchersBoy** [comment]
Yeah...this is one of the last big holes in the API...hopefully I will get to it soon.

**Comment by QuantumDeveloper** [comment]
@ButchersBoy can you also take into consideration this when you will implement side panels (tool windows)? Possibility to control tab position from MVVM would be a greate feature

**Comment by ButchersBoy** [comment]
Will do, but as discussed previously, phased in.  First thing we need is a method to be able to split the Layout in code on the fly.  Then, when in used in conjunction with the existing ```TabablzControl.AddItem``` method you will be able to create everything you can _currently_ do with the mouse in code.  We already have the query API, so completing this would leave you fully able to save/restore the layout in user code.

So initially, lookout for some kind of ```Layout.Split``` method...I'll try and get to this in the next week or two.

**Comment by QuantumDeveloper** [comment]
ok, looking forward to this.

**Comment by ButchersBoy** [comment]
You can now split the layout in code using the ```Layout.Branch``` method.  Please run up the test app and play with this screen:

![branchapi](https://cloud.githubusercontent.com/assets/658107/10003711/ce73ac1a-60a5-11e5-9032-34006c2151f7.gif)

Search for usages of Layout.Branch to see how to use it (documentation is scarce at the moment).

Couple of things:
* ratio is included in the API, but not plugged in as of writing
* when the windows get small, they suddenly expand in size when tearing out.  I am aware of this issue.

**Comment by QuantumDeveloper** [comment]
One more issue: when maximize window, it does not fit to the task bar (dont know is it already was reported)

And another regarding dragablz: Could you make that if I drop tab into center, it not tirn to mdi window by default, but just appears it the center like in VS? Just separate tab in it own container with width and height by default like all other tabs in your examples? Is it possible?

**Comment by ButchersBoy** [comment]
@QuantumDeveloper Set this value to False (or just remove):

```<dockablz:Layout IsFloatDropZoneEnabled="True" />```

This will remove the central zone for dropping into a tool window/MDI.  There isn't one for dropping into the central tab zone as a) there is no central tab zone with this layout concept and b) individual branches can get too small.

Hopefully this will become apparent over the next couple of updates; I've got a couple more things coming which will show where this is going...

**Comment by QuantumDeveloper** [comment]
@ButchersBoy aha, ok. Sorry. I thought that central drop zone is also mde for tabs.

**Comment by ButchersBoy** [comment]
Well kinda...the idea being that if you want, you can take a tab, and drop it straight into a tool window...so a kinda slightly different take on your VS type docking.

**Comment by QuantumDeveloper** [comment]
Hm... ok, I understood. Will wait your further updates.

**Comment by ButchersBoy** [comment]
The  ```Layout.Branch()``` method now accepts ```firstItemProportion``` so size of a branch can be set from code.

And you can get the current proportions of a split from ```Branch.GetFirstProportion()```

This is a pretty big step, now Windows/tabs/branches can all be restored from code (Floating windows still to do), if you follow a sequence of steps to restore your layout.  You can see this from this demo page:

![image](https://cloud.githubusercontent.com/assets/658107/11029448/ec68ce82-86be-11e5-9748-d545bbb0c3f8.png)

**Comment by simplykayy** [comment]
Hi thank you for this awesome library. An issue i can't seem to resolve is how to set the position of the floating item. By default it is positioned to the top left of my app window. Is it possible to change this default?

Thank you

**Comment by ButchersBoy** [comment]
@simplykayy there are still some parts of the API to finalise around the floating items; the big one being able to manage where the initially appear...so work on that is pending.

**Comment by simplykayy** [comment]
Thank you for your prompt feedback. Another question, the TabablzControl ClosingItemCallback routed event, does that work with blend sdk interactive triggers? I have gone down the route of MVVM and was thinking i'd hook that event into the blend sdk interaction event but it doesn't seem to work....any guidance. Below is a sample code => 

<dragablz:TabablzControl ShowDefaultCloseButton="True" ItemsSource="{Binding TabContents}" 
                             AdjacentHeaderItemOffset="1" Margin="0 5 5 5" IsEnabled="True"
                             Visibility="{Binding ShowDeviceInteraction, Converter={StaticResource BooleanToVisibilityConverter}}">
        <i:Interaction.Triggers>
            <i:EventTrigger EventName="ClosingItemCallback">
                <i:InvokeCommandAction Command="{Binding OnTabClosedCommand}" />
            </i:EventTrigger>
        </i:Interaction.Triggers>
        <TabControl.ContentTemplate>
            <DataTemplate>
                <ContentPresenter Content="{Binding Content}" />
            </DataTemplate>
        </TabControl.ContentTemplate>
    </dragablz:TabablzControl>
