### ISSUE TITLE
tab movement does not work for multiple windows under different instance

### ISSUE THREAD

**Issue by saugat** [ButchersBoy/Dragablz#42]
When you start two different instance of program and try to move one tab from another,unlike chrome it wont work. Chrome allows tab movement from one window to another regardless of its instance creation but demo your dll simply treats it as a different process and tab movement doesnot work. 
If possible, I would like to see this implemented in your library.

**Comment by ButchersBoy** [comment]
Dragablz is strictly in process.  But I have achieved the effect (I think) you are after by using a Mutex to enforce a single process instance: delegate requests to start a new Window back to your existing process instance and silently shut down the new instance.  This also means you can start using Windows Jump Lists with Dragablz and get quite a nice experience.

I'll try and knock up a demo app/blog on how to do this.
