### ISSUE TITLE
Give possibility to set AddButton to the far right edge of the dragablz

### ISSUE THREAD

**Issue by QuantumDeveloper** [ButchersBoy/Dragablz#43]
Hi, I wish you give such possibility, because I think its not so convenient when pressing add button make this button move. It should be pinned and placed at the right side like in web browsers. So, creating few tabs one after another will not need to move mouse and chase for the button.

What do you think?

**Comment by ButchersBoy** [comment]
It was _almost_ possible before, apart from a bit of alignment.  I just pushed a small change so now you can achieve this affect.

Is you use ```ShowDefaultAddButton="True"``` all it does is call to the command ```TabablzControl.AddItemCommand```.

So the solution is not to use the default add button, but your own:

```
<dragablz:TabablzControl ShowDefaultAddButton="False">
   <dragablz:TabablzControl.HeaderSuffixContent>                
       <Button Command="dragablz:TabablzControl.AddItemCommand" Style="{StaticResource AddItemCommandButtonStyle}"
               HorizontalAlignment="Right"/>                                    
   </dragablz:TabablzControl.HeaderSuffixContent>
</dragablz:TabablzControl>
```

**Comment by QuantumDeveloper** [comment]
OK, thanks for that.
