### ISSUE TITLE
Selecting the first opened tab after closing another one could be annoying

### ISSUE THREAD

**Issue by adimitrov93** [ButchersBoy/Dragablz#47]
After closing a tab, the tab which is being selected is the one which was first opened, which can be very annoying. Better solution - after close to select the last selected tab. Or the one which is last in order. I will be implementing the first scenario (with the last selected tab), so if you want I could implement it in the control and make a pull request.

**Comment by ButchersBoy** [comment]
Hey, yes, a PR for this would be welcome.
