### ISSUE TITLE
DefaultInterLayoutClient crash

### ISSUE THREAD

**Issue by iainnicol** [ButchersBoy/Dragablz#48]
Dragablz is amazingly slick.

However, I can cause the StylezApp example to crash.

Drag one of the Introduction tabs to dock it in the bottom half of the window.  Then click the Add tab button.  It crashes because NewItemFactory is not set.

Perhaps DefaultInterLayoutClient should copy the NewItemFactory property.  Whilst we're at it, it also seems like DefaultInterLayoutClient doesn't copy the InterTabClient, at least if it was InterTabClient was set with a XAML binding.  Can this be fixed, or is there no good solution when those properties were set in XAML as bindings?

**Comment by ButchersBoy** [comment]
Yeah, always a bit tricky copying the values...I'll try and have a look over the next few days...

**Comment by ButchersBoy** [comment]
...ahh just remembered I fixed that in one of the other demos...where the solutions is just to make sure the binding evaluates to something on the new Window/DataContext.  I'll get this app with the same fix.

**Comment by iainnicol** [comment]
Cool, thanks.

**Comment by ButchersBoy** [comment]
Fixed demo, (changed binding in App.xaml)

**Comment by iainnicol** [comment]
Thanks again.  I see it was a straightforward fix.
