### ISSUE TITLE
Use Strong Names for the Nuget Package

### ISSUE THREAD

**Issue by ksenkevich** [ButchersBoy/Dragablz#50]
It would be nice for the Nuget Package to use strong named assemblies

**Comment by ButchersBoy** [comment]
Are you trying to reference from another strong named assembly?

**Comment by ksenkevich** [comment]
That is what I want to do.  Currently, I have a fork of the repository that I am signing the projects in.

**Comment by ButchersBoy** [comment]
Have you tried this? https://github.com/dsplaisted/strongnamer

I haven't tried it, but am hearing positive things...

**Comment by ButchersBoy** [comment]
The above is recommended route.
