### ISSUE TITLE
WindowsFormsHost doesn't display on DragablzWindow

### ISSUE THREAD

**Issue by cnelson711** [ButchersBoy/Dragablz#51]
When using the example DragablzWindowApp project, I have a custom user control that I am trying to host in a WindowsFormsHost.  The custom user control does not appear when the main window is a DragablzWindow.

The form works as expected when I change the inheritence of the main window to a System.Windows.Window.

**Comment by ButchersBoy** [comment]
Oh man.  WinForms.  :)

The DragablzWindow is basically a normal WPF borderless windows...not quite sure what's going on without trying, I have never tried hosting WinForms controls.  I will try and have a look.

Incidentally, have you tried this on a MahApps MetroWindow?

**Comment by QuantumDeveloper** [comment]
Om MA window it works, because WindowsFormsHost is legal WPF control and should always display its content :)

**Comment by svantreeck** [comment]
You can make this work by setting AllowsTransparency=false on the containing window, but expect that the UX will look worse with the window border.

**Comment by ButchersBoy** [comment]
Thanks @svantreeck 

@cnelson711 ...in which case you are probably better off using a normal Window or MahApps.MetroWindow

**Comment by cnelson711** [comment]
The custom user control shows up on MetroWindow and Window, but doesn't on DragablzWindow.

I'm also having headaches with the custom control's size while resizing the window.  I just want the custom control to be the content of my tabs.

**Comment by ButchersBoy** [comment]
Yeah...there's tradeoffs with each Window.

The DragablzWindow (which is basically a borderless Window) will give you the cut out shape, but you can't get any shadow behind it.  And as we now know you can'y host a WinForms control in it.  A normal Window or MetroWindow will give you a nice shadow but you can't get the cut-out shape.

So basically, you have to choose your poison :skull: ...unfortunately there isn't a Window type which achieves everything.

Having said that I need to have a look at what can be achieved with https://msdn.microsoft.com/library/system.windows.interop.hwndsourceparameters.usesperpixeltransparency.aspx which is in .Net 4.6

**Comment by cnelson711** [comment]
I'm closing this issue as svantreeck's AllowTransparency = false; and having the window border show back up is acceptable to me.
