### ISSUE TITLE
Window Command Buttons/Float Item

### ISSUE THREAD

**Issue by MurariAlex** [ButchersBoy/Dragablz#52]
Hi,

Testing in Window 10 the sample app, I found an wrong behavior in the float item.

When you expand the float window to full parent window size, the command buttons gets behind the parent window's command buttons:
![dragblzissue](https://cloud.githubusercontent.com/assets/11204378/10734848/5eabfce0-7bec-11e5-8e5f-80d7f380cad6.jpg)

Dunno if it`s a bug, or can just be set via code to disable this behavior.

BTW, good work on the DPI issue, nailed it. :)

**Comment by ButchersBoy** [comment]
OK...what type of Window are you using?

**Comment by MurariAlex** [comment]
It's the DragblzDemo project, untouched.
The .NET 4.0 executable.

**Comment by ButchersBoy** [comment]
OK, moving the window buttons behind the floating windows, and also adding ```Layout.FloatingItemsContainerMargin``` to give you some extra flexibility.
