### ISSUE TITLE
Allow tabs to be torn out to a new window that is a different window then the source window

### ISSUE THREAD

**Issue by ksenkevich** [ButchersBoy/Dragablz#53]
I have created a sample application here: https://github.com/ksenkevich/DragablzTestApp.  What I would like to do is when a tab tears out it stays the same size as it was in the tab control with the tab control not being the full size of the window.  Currently, it is using the size of the parent window.  It seems like this would just require some modifications to the MonitorBreach method in the TabablzControl.

**Comment by ButchersBoy** [comment]
OK
