### ISSUE TITLE
Where is the definition of MahAppsTabHeaderItemStyle in DragablzModernUIDemo?

### ISSUE THREAD

**Issue by finesay** [ButchersBoy/Dragablz#54]
Emm, I could not find any style named "MahAppsTabHeaderItemStyle" in DragablzModernUIDemo.

**Comment by ButchersBoy** [comment]
Hi @finesay 

DragablzModernUIDemo is defunct; it has been for a while.  For MahApps samples check this repo: https://github.com/ButchersBoy/DragablzSamplez

...is there some documentation laying around somewhere I haven't removed?  :)

**Comment by finesay** [comment]
@ButchersBoy 

I just find a using of `MahAppsTabHeaderItemStyle` in [MainWindow.xaml](https://github.com/ButchersBoy/Dragablz/blob/master/DragablzModernUIDemo/MainWindow.xaml)(LINE 21) , but not trivial.

Thanks a lot.
