### ISSUE TITLE
HeaderSuffixContent set to grid with 74 width

### ISSUE THREAD

**Issue by mrfrostfire** [ButchersBoy/Dragablz#55]
By default the headersuffix will take up 74px of space for no understandable reason.
This leaves a 74px gap of useless space in a tabheader unless overridden.
The default should be a grid of no size to allow the tabcontrolheader to take up all the space without having to specify a suffix.

The code:
        <Setter Property="HeaderSuffixContent">
            <Setter.Value>
                <Grid Width="74" />
            </Setter.Value>
        </Setter>

Should be:
        <Setter Property="HeaderSuffixContent">
            <Setter.Value>
                <Grid />
            </Setter.Value>
        </Setter>

**Comment by ButchersBoy** [comment]
The reason it's there is because I was having trouble with sizing/measuring of the tab header strip, tabs pushing up - and then over - towards the standard Window buttons & scroll bars, all cuasing a bit of a layout issue.

Yes...it's not right, but there is some history behind it.

I'll try and revisit it, resolve the underlying issue and remove the default.

**Comment by mrfrostfire** [comment]
gotya .. i'm kind of in the same position now.
I'm trying to get the dragablzitemscontrol to size properly, and I got it to work partly, but that kind of stuff is always a pita.

**Comment by ButchersBoy** [comment]
I'll try and improve...

**Comment by ButchersBoy** [comment]
@mrfrostfire which style and window are you using?

**Comment by mrfrostfire** [comment]
I only need the dragablz for the ability to drag tabs around, so i've tried to keep it as native as possible.
So i'm just using it as a tabcontrol with ability to drag tabs around if that helps.

**Comment by mrfrostfire** [comment]
Btw, I used the MaterialDesign style as the base and have modified it to what we need it for.
There's still problems with the sizing though causing limitations due to the meassureoverride etc.
I get that the canvas is causing issues due to it not reporting any size. But can't that be solved by specifying it's width/height based on the content inside instead of having a meassureoverride on the itemscontrol etc?

**Comment by ButchersBoy** [comment]
The MeasureOverride in DragablzItemsControl is a pretty fundamental requirement to figure out how big the content is, according to the IItemsOrganiser; which is plug-able.

**Comment by mrfrostfire** [comment]
ok, then just replacing it might be a bit hard.
So here's the issue i'm currently at:
We want to have the tabs inside a scrollviewer to be able to do horizontal scrolling if there's not enough room to fit all the tabs into the area.
While doing that, we want to have the defaultaddbutton flowing to the right of the tabs as it is per default.
The addbutton however should be outside the scrollviewer as it should always be visible.
I haven't been able to find any combination of that scenario that works, since either the addbutton is pushed out because the itemscontrol takes up too much space, or it gets aligned wrong.
Do you have any suggestions?

**Comment by ButchersBoy** [comment]
Can you post a sketch of that?  

My intent is to remove the default suffix, and rework the style a bit, so when I do that I'll try and get your requirement working.

**Comment by mrfrostfire** [comment]
![dragablz scrollviewer](https://cloud.githubusercontent.com/assets/3914832/10940956/825f17ca-8309-11e5-80f8-2a2cce9a0b04.png)
Here's a pic of the header using styled dragablz before the scrollviewer is activated and after.
I hope that helps

**Comment by mrfrostfire** [comment]
And thanks!

**Comment by ButchersBoy** [comment]
Nice theme :+1:

**Comment by mrfrostfire** [comment]
Thanks :)

**Comment by ButchersBoy** [comment]
So yeah, turned out to be a 1 liner, where I wasn't measuring the default add button when calculating the size of the header strip, so incoming will give you this:

![image](https://cloud.githubusercontent.com/assets/658107/10944108/6061ce1e-830f-11e5-89d0-59d4bb1de321.png)

**Comment by ButchersBoy** [comment]
GitHub auto-closes issue...but please let me know if this is OK with your style...

**Comment by mrfrostfire** [comment]
i'll try it out asap .. probably tomorrow

**Comment by mrfrostfire** [comment]
Thank you! Worked like a charm.
Since I have the scrollviewer around the dragablzitemscontrol, I moved the maxwidth binding to the scrollviewer and bound the dragablzitemscontrols maxwidth to its own ItemPresenterWidth.
This makes sure to compensate for any additional size the scrollviewer might take up.

**Comment by ButchersBoy** [comment]
:+1:
