### ISSUE TITLE
Ability to add clickable buttons to header

### ISSUE THREAD

**Issue by svantreeck** [ButchersBoy/Dragablz#57]
I'd like to be able to add a toggle button into the header so users could toggle a view as being a "favorite" within the application, but it appears that the template used for the style sets IsHitTestVisible=false on the underlying content control, and as a result, the toggle button in my CustomHeaderItemTemplate is not clickable.  I've tried tweaking it to have IsHitTestVisible=true on it, but I'm not sure if there's a good way of doing this.

Any ideas?  I think the IsHitTestVisible also makes it so that tooltips aren't working in the header as well.

````
<dragablz:TabablzControl.CustomHeaderItemTemplate>
                <DataTemplate>
                    <StackPanel Orientation="Horizontal">
                        <ToggleButton Style="{StaticResource FavoriteToggleButton}">
                        </ToggleButton>
                        
                        <TextBlock FontWeight="SemiBold" Text="{Binding Title}" 
                                       TextTrimming="CharacterEllipsis" VerticalAlignment="Center"
                                       MaxWidth="200" />

                        <TextBlock Text="*"
                                       FontWeight="SemiBold" 
                                       VerticalAlignment="Center" 
                                       Visibility="{Binding IsDirty, Converter={StaticResource BooleanToVisibilityConverter}}"/>

                    </StackPanel>
                </DataTemplate>
            </dragablz:TabablzControl.CustomHeaderItemTemplate>
````

**Comment by ButchersBoy** [comment]
Yeah, this is possible. In the demos, check out this tab:

![image](https://cloud.githubusercontent.com/assets/658107/11076832/d6f67978-87f4-11e5-9769-b86f7543e928.png)

Then look at CustomHeader.xaml in DragalzDemo.  You will see you have to provide your own Thumb, and tell Dragablz that it's your custom thumb, then you can add your Checkbox to the side:

```
<StackPanel Orientation="Horizontal">
    <Grid>                     
        <TextBlock Text="{Binding Header}" />
        <!-- you should provide your own Thumb, which will be used to monitor dragging -->
        <Thumb Style="{DynamicResource InvisibleThumbStyle}"
               dragablz:DragablzItem.IsCustomThumb="True" />
    </Grid>        
    <CheckBox IsChecked="{Binding IsSelected}" ToolTip="Embed your own controls" />            
    <Button ToolTip="Manually add a close button"
            Command="dragablz:TabablzControl.CloseItemCommand"
            >X</Button>
</StackPanel>
```

Check for usages of ```CustomHeader``` to see how it's applied to the tab control.

**Comment by svantreeck** [comment]
Thanks, that will work perfectly

**Comment by svantreeck** [comment]
Unfortunately, I think the MahApps.xaml theme is breaking the custom thumb due to IsHitTestVisible=false (https://github.com/ButchersBoy/Dragablz/blob/master/Dragablz/Themes/MahApps.xaml#L178) on the ContentPresenter.  When I compare it to the generic theme, what I'm trying to do works just fine.  Any idea if IsHitTestVisible could be removed?

Thanks

**Comment by ButchersBoy** [comment]
OK, I'll check it out.

**Comment by ButchersBoy** [comment]
OK now?

**Comment by svantreeck** [comment]
Yeah, thanks for the quick turnaround
