### ISSUE TITLE
Close button is not getting displayed

### ISSUE THREAD

**Issue by jithurjacob** [ButchersBoy/Dragablz#58]
Hi I'm developing an application in WPF C# where I use Material Design and dragablz. I don't need features like docking I've disabled InterTabController as I'm using dragablz inside a user component.

  public INewTabHost<Window> GetNewHost(IInterTabClient interTabClient, object partition, TabablzControl source)
        {
            var view = new UserControl2();
            var model = new BoundExampleModel();
            view.DataContext = model;
            return new NewTabHost<Window>(view, view.InitialTabablzControl);
        }
Here view can only be a window. The Issue I'm facing is I'm not getting close button with tabs (add button is working)

**Comment by ButchersBoy** [comment]
Have you got ```.ShowDefaultCloseButton``` button set?

**Comment by jithurjacob** [comment]
Yes

**Comment by jithurjacob** [comment]
<Window x:Class="Wpf_test.tab_test"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:Wpf_test"
        xmlns:domain="clr-namespace:Wpf_test.Domain"
        xmlns:dragablz="clr-namespace:Dragablz;assembly=Dragablz"
        mc:Ignorable="d"
        Title="tab_test" Height="300" Width="300">
    <Window.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/Dragablz;component/Themes/Generic.xaml" />
            </ResourceDictionary.MergedDictionaries>
            <DataTemplate DataType="{x:Type dragablz:HeaderedItemViewModel}">
                <ContentControl Content="{Binding Content}" Margin="4 4 4 4" FontSize="14" />
            </DataTemplate>


            <dragablz:DragablzIcon Width="24" Height="24" Margin="0 -8 0 0"
                                   x:Key="WindowIcon" x:Shared="False"
                                   ToolTip="Added via the HeaderPrefixContent property"
                                   />
            <Style TargetType="{x:Type dragablz:TabablzControl}" x:Key="TabablzControlStyle">
                <Setter Property="NewItemFactory" Value="{x:Static domain:BoundExampleNewItem.Factory}" />
                <Setter Property="ShowDefaultCloseButton" Value="True" />
                <Setter Property="ShowDefaultAddButton" Value="True" />
                
                <Setter Property="ClosingItemCallback" Value="{Binding ClosingTabItemHandler}" />

                <Setter Property="AdjacentHeaderItemOffset" Value="10" />

                <Setter Property="HeaderMemberPath" Value="Header" />

                <Setter Property="Margin" Value="0 10 0 0" />
            </Style>
        </ResourceDictionary>
    </Window.Resources>
    <Grid>
        <dragablz:TabablzControl x:Name="InitialTabablzControl" Padding="0" Style="{StaticResource TabablzControlStyle}" UseLayoutRounding="True" BorderThickness="0,1,0,0">
            
            <TabItem Header="HELLO">
                <InlineUIContainer>
                    <Button x:Name="button" Content="Button" Width="75"/>
                </InlineUIContainer>

            </TabItem>

            <TabItem Header="MATERIAL">
                <TextBlock HorizontalAlignment="Center" VerticalAlignment="Center">Material Design</TextBlock>
            </TabItem>
            <TabItem Header="DESIGN">
                <TextBlock HorizontalAlignment="Center" VerticalAlignment="Center">Looks Quite Nice</TextBlock>
            </TabItem>
        </dragablz:TabablzControl>
    </Grid>

**Comment by ButchersBoy** [comment]
Hi ```.ShowDefaultCloseButton``` will also need to be set on your UserControl2/second Window....you sure this is being applied?  As this should be working.

**Comment by ButchersBoy** [comment]
Is this an issue still? If so, post a repo please.  Otherwise I'll close.

**Comment by jithurjacob** [comment]
I was to able to solve this. Thank you

**Comment by yvasilev1** [comment]
How did you fix it im encountering the same issue?

**Comment by babin1988** [comment]
I have used ".ShowDefaultCloseButton" but didn't solved the issue. You can have a look on my code: 
`<dockablz:Layout>
        <dragablz:TabablzControl Margin="0" BorderThickness="0" ShowDefaultCloseButton="True">
            <dragablz:TabablzControl.InterTabController>
            <dragablz:InterTabController />
        </dragablz:TabablzControl.InterTabController>
            <TabItem Header="Tab No. 1" IsSelected="True">
                <TextBlock>Hello World</TextBlock>
            </TabItem>
            <TabItem Header="Tab No. 2">
                <TextBlock>We Have Tearable Tabs!</TextBlock>
            </TabItem>    
        </dragablz:TabablzControl>
    </dockablz:Layout>`

**Comment by babin1988** [comment]
Previous issue was solved. 
Now I want first tab of the tabcontrol should not have the close button. How could I implement it?

**Comment by ButchersBoy** [comment]
@babin1988 ``` FixedHeaderCount ```

**Comment by ZeyadAttia** [comment]
> I was to able to solve this. Thank you

How?
