### ISSUE TITLE
Is there a way to use Dragablz in a window with Material Design in XAML Toolkit?

### ISSUE THREAD

**Issue by SuicSoft** [ButchersBoy/Dragablz#59]
Is there anyway to use a Dragablz TabControl as a window while using the Material Design in XAML Toolkit?

**Comment by ButchersBoy** [comment]
Ho do you mean?  You've checked the "Mashup" demo, right?

**Comment by SuicSoft** [comment]
Yes, but I mean "as" a window, like Chrome Browser.

On Mon, Nov 16, 2015, 7:18 PM James Willock <notifications@github.com>
wrote:

> Ho do you mean? You've checked the "Mashup" demo, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ButchersBoy/Dragablz/issues/59#issuecomment-157031031>
> .
>
-- 
The Studio/Software Dog,
Suici Doga

Sent from Inbox by Gmail

**Comment by ButchersBoy** [comment]
At the moment you options are a normal Window the DragablzWindow, or MahApps.MetroWindow, and all have their advantages/disadvantages, so really you've got to just pick your best fit...or create your own...
