### ISSUE TITLE
Windows Forms Host Keyboard Shortcuts

### ISSUE THREAD

**Issue by svantreeck** [ButchersBoy/Dragablz#63]
I'm having some difficulties where a Tab Control that contains a WindowsFormsHost can take keyboard input when not being the active tab.  When looking in the visual tree, it looks like the inactive tab continues to exist.  As a result, if I have a WinForms button when text of "&A", if someone is on a different tab and presses "A", the inactive tab that contains the WinFormsHost/Button seems to eat the keystroke and the WinForms button's clicked event is triggered.

When I compare this to the normal windows tab control behavior, it appears that the normal tab control only [presents the selected tab's contents](https://msdn.microsoft.com/en-us/library/ms754137(v=vs.100).aspx) which prevents the WinFormsHost from eating the keystroke.  Is there a reason behind having the inactive tabs in the "PART_ItemsHolder" section?  

Would you have any recommendations on resolving this?  I was considering listening to selected tab changed event and hiding the non-selected controls, but it seems like I'd be doing something unnecessary.

Thanks

**Comment by ButchersBoy** [comment]
The "caching" is a to solve a problem with the WPF TabControl; namely performance.  Anything more than basic WPF visual tree can cause sticky-ness switching between the tabs.

The flip-side is (for WPF at least) is we now hold on to many more visual.

A longer term goal is to allow a pluggable cache-ing strategy. In your case a strategy of "none" would probably do the trick.  But, I want to get the API right, to allow for ageing scenarios etc to give more granular control over this, so not going to jump in and make a hack just now - got too much other work on at the moment, but hopefully I can get to this over Christmas when my time frees up a bit.

**Comment by svantreeck** [comment]
Great, I think for now, I'll fork the current implementation to meet my needs, and look forward to seeing the caching strategy in the future

**Comment by ButchersBoy** [comment]
re-opened and renamed to keep track.

**Comment by svantreeck** [comment]
It looks like it might actually be a bug in the WindowsFormsHost.  From some experimentation, it looks like setting the Visibility on the WindowsFormsHost along with the parent ContentPresenter fixes the issues I was seeing with Hotkeys.  You can check out what I was doing on [this commit](https://github.com/svantreeck/Dragablz/commit/f5c13712e23669ee4c0dc37b2805966c1b741444#diff-34bbf2ec2c79d544a4612f37bc27970c).  

I'm going to see if I can move that code into the SelectedItem changed event in my app to continue to use the non-modified dragablz tab control and see if I can find a better workaround.

**Comment by svantreeck** [comment]
I found a solution for this that would basically toggle IsEnabled on the ContentPresenters when the visibility changes, which seems like it will fix the underlying issue.  If you don't have any problems, I think it would be a low impact change that would work prior to the caching changes, and I can create a PR for the change.

**Comment by ButchersBoy** [comment]
OK, sounds reasonable.  Submit a PR and I'll test it.
