### ISSUE TITLE
SetIsWrappingTabItem Visibility

### ISSUE THREAD

**Issue by tstephansen** [ButchersBoy/Dragablz#65]
I wrote some xaml a while back to customize the look and I copied for a while I've been having to change the following methods from internal to public and recompile to use them in my program. Would it be possible for you to make them public in the next release? They are from TabablzControl.cs If not, I understand. I just thought I would ask you and find out before I continued my current process.

Proposition:

~~`internal static void SetIsWrappingTabItem(DependencyObject element, bool value)`~~
````
public static void SetIsWrappingTabItem(DependencyObject element, bool value)
{
    element.SetValue(IsWrappingTabItemProperty, value);
}
````
~~`internal static bool GetIsWrappingTabItem(DependencyObject element)`~~
````
public static bool GetIsWrappingTabItem(DependencyObject element)
{
    return (bool) element.GetValue(IsWrappingTabItemProperty);
}
````

Thank you!

**Comment by ButchersBoy** [comment]
Hi, will your XAML work with just the getter marked as public?

**Comment by tstephansen** [comment]
It does work with only the getter being public.

**Comment by ButchersBoy** [comment]
Sounds like we have a plan :smile: 

Want to submit a PR?

**Comment by tstephansen** [comment]
Thank you! I will as soon as I can get back to my desk.
