### ISSUE TITLE
Unable to dtect if a TabItem is being removed from a collection and not being moved to a new window

### ISSUE THREAD

**Issue by adantiff** [ButchersBoy/Dragablz#67]
Is there a way to detect if a TabItem is being removed from a collection and not being moved to a new window? The reason I'm trying to do this is to make sure my application properly disposes of the DataContext objects when a tab is closed (either manually via the built-in tab close button, or programmatically). I can partially achieve this with the following code

* MainTabs being my bound ObservableCollection<TabContent>

 MainTabs.CollectionChanged += (s, ev) =>
            {
                if (ev.Action == System.Collections.Specialized.NotifyCollectionChangedAction.Remove)
                {
                    
                    foreach (TabContent deletedTab in ev.OldItems)
                        if (deletedTab.Content is _Class_)
                            (deletedTab.Content as _Class_).DataContext = null;

                }
            };

This will result in memory properly being disposed of (when closed), but blanks out the Content object if the tab is being dragged into a different Window, since it can't tell the difference. I did notice **TabablzControl.GetIsClosingAsPartOfDragOperation(Window)** , but am unsure if this can be used for my problem, and if so how to use it since it doesn't refer to the TabItem.

Thanks for your time, great work!

**Comment by ButchersBoy** [comment]
Are you using ```ShowDefaultCloseButton``` (or ```CloseItemCommand```)?

If so you can hook into ```ClosingItemCallback```.
