### ISSUE TITLE
Tabs Scroll Bar Position

### ISSUE THREAD

**Issue by Hikerakashiya** [ButchersBoy/Dragablz#71]
After adding a number of tabs that fills the window, the scroll bar displays. However it appears the position of this scroll bar is not right. The scroll bar appears with the right arrow being cut off/clipped by the window.

![dragablzscroller](https://cloud.githubusercontent.com/assets/12399352/12100874/b3303584-b2ff-11e5-98fe-d29ff1fe80da.png)

Is there any way to fix this? It appears to be a problem with all of the demos once you have enough tabs. 

Also is there a way to have the scroll bar to display a left arrow on the left side and the right arrow on the right side so the tabs are between the arrows? Having the option to have no scroll bar and just have the tabs in rows would be great too.

**Comment by ButchersBoy** [comment]
Hi, are you running an old version there?

Currently it looks like this, a bit of overlap but a lot better - which I will improve:

![image](https://cloud.githubusercontent.com/assets/658107/12101785/7fe3c644-b32e-11e5-9ee9-ce12092c682f.png)

As for the other two requests.  Both buttons are together to save the user having to move from one side of the screen to another to go back and forth.  But a style could be created to have the buttons left and right; but this isn't something that I am going to tackle just now as it will add yet more complexity and what I have so far isn't finished yet.

As for rows, yes, I want to do that but it's a way off yet as this will bring even more complexity, and I need to tidy up the current functionality.

**Comment by Hikerakashiya** [comment]
I am running the current version The funny thing, I originally was going to include the same screenshot you just posted. I wound up turning off the add button. If you set ShowDefaultAddButton="False" your screenshot will turn into the screenshot I posted.

I brought up the left and right side arrows because that is how Pidgin has it implemented and was hoping to implment something similar in my project.

![pidgin](https://cloud.githubusercontent.com/assets/12399352/12102131/c70ee576-b306-11e5-8637-b1225919b049.png)

How easy would it be to fix the arrow placement how it currently is?

**Comment by ButchersBoy** [comment]
You mean fix it with both arrows on left?  Shouldn't be too difficult...just a couple of pixels out somewhere.

If you want to replicate Pidgen you can create your own style, you'll just need to change the ScrollView template which is set internally in the current template.

**Comment by Hikerakashiya** [comment]
I mean to fix it where the arrows are not clipped on the right side of the window. In both our screenshots whether you have the Add Button enabled or disabled the arrows that appears on the right side when the tabs overflow are being cut off/clipped by the window. If there is a way to fix that easily that would be great.

![dragablzscroller2](https://cloud.githubusercontent.com/assets/12399352/12102387/699beca2-b308-11e5-8dec-17b46e0d8b77.png)

If I wanted to try to replicate the Pidign functionality where the left arrow is on the left and the right arrow is on the right, where/ how would I begin?

**Comment by Hikerakashiya** [comment]
Is there a way to easily fix the arrow placement I circled in red in my previous comment? I just need the arrows to not be cut off when they are displayed.

**Comment by ButchersBoy** [comment]
I will try and fix it as soon as I have opportunity, otherwise you can start digging into the template for TabablzControl and have a look where it's going wrong...

**Comment by ButchersBoy** [comment]
Incoming:
![image](https://cloud.githubusercontent.com/assets/658107/12266011/802f2e76-b938-11e5-938a-8c44d84daac9.png)

**Comment by Hikerakashiya** [comment]
You rock!

**Comment by ButchersBoy** [comment]
ha, :100: points !

**Comment by ButchersBoy** [comment]
(nuget version 0.0.3.149 onwards)
