### ISSUE TITLE
Need a way to reposition suffix control to start (left) position after closing last tab

### ISSUE THREAD

**Issue by AdrianKole** [ButchersBoy/Dragablz#72]
Is there a way to have the last (rightmost/suffix/add new) TabablzControl tab always repositioned to the far left (starting) position after removing the last content tab? Right now, that last tab does not appear to close the gap made after removing the last content tab. We do not close the window when the last tab is closed.  Setting FixedHeaderCount > 0 is not really an option for us as we don’t have an “always visible” tab to show.

As you mentioned, the gap is currently for allowing dropping an item--something for which we currently have no use.  We just allow for adding tabs via the always visible suffix control, which presents a menu of options for a new tab's content.

Thanks for providing such a cool control!

**Comment by ButchersBoy** [comment]
OK, the fact you have clarified the fact that you wont be dragging into your empty window is helpful: in this case I should be able to provide a single flag to get the behaviour you want.

**Comment by AdrianKole** [comment]
Terrific!  Thank you.

**Comment by AdrianKole** [comment]
I just wanted to point out that sometimes the suffix tab will also show a gap even when there still is a content tab showing (i.e. it's not just when the last content tab is removed that the gap can show).  For instance, adding two tabs shows <content 1> <content 2> <suffix>; after removing <content 2> the tab control will show <content 1> [gap] <suffix>.  (Though, oddly enough, if another sequence was used this will not always be the case and a gap would not be shown)  My hope is that your new flag could control whether the suffix tab is always left-justified.  Thank you.

**Comment by ButchersBoy** [comment]
@AdrianKole Please see the new ```EmptyHeaderSizingHint``` property.

I think the other thing you have mentioned is more of a dispatcher thing where we need to kick off a new arrange....

**Comment by AdrianKole** [comment]
I downloaded your changes from the last commits of yours I did not have (and also had to carefully edit the code to remove the null-conditional operator instances and replace them with explicit null tests as we are still using VS 2013).

Unfortunately, if I add the EmptyHeaderSizingHint attribute to a TabablzControl, I end up with a NullReferenceException thrown.  This happens regardless of the value assigned to it ('Collapse' or 'PreviousTab').  Removing the attribute allows the application to start up normally as before getting the latest commits.

The exception unfortunately doesn't have much in the way of detail.  InnerException is null.  The StackTrace property contains "   at System.Windows.Baml2006.Baml2006Reader.Process_PropertyWithConverter()".

Ideas?

**Comment by ButchersBoy** [comment]
OK, i'll have a look

**Comment by AdrianKole** [comment]
It looks like it may be something different with my project that is causing the problem.  IIRC, earlier today I tried to use the new Dragablz.dll (with the merged in changes) instead with your demo application and even with the attribute added to one of your controls it worked without an exception thrown.  This may at least help rule out the possibility that I incorrectly merged in the new changes.

However, even after having commented-out most all of the XAML in the main window of my project and pasting in a TabablzControl element snippet adapted from your QuickStart example, I could still reproduce the problem if and only if I set the new EmptyHeaderSizingHint attribute on it!  Very strange.

I wish I had more details from the exception.  It would appear from the stack trace that core WPF code is trying to access some property (a new DependencyProperty that's not yet initialized?) and encountering the exception.  If you want, I could e-mail a screenshot of the debugger that provides a deeper stacktrace than just the top of the stack that is provided with the StackTrace property (please let me know the e-mail address to use if you want this--or if there is some way of posting that here).

I'm not sure if it's relevant, but in your projects I have added code signing to the binaries (our code is signed and in order to use your DLL, your DLL needs to be signed too).  This did not cause a problem before and your demo works with this setup too; I just thought I'd point that out.

**Comment by ButchersBoy** [comment]
If all you are doing with your fork is strong naming then I suggest you have a look at [StrongNamer](https://github.com/dsplaisted/strongnamer) and then report back from the official build...

**Comment by AdrianKole** [comment]
Thanks for the suggestion.  I can keep that in mind in possible future projects.  In this case, however, I do indeed need changes that I added.

**Comment by ButchersBoy** [comment]
I did find a bug, which is fixed and tested...but I don't see how it is related to the issue you are seeing.  If you can reproduce it, with the official nuget .dll then post a git repo and re-open this issue.

**Comment by AdrianKole** [comment]
Silly me:  the application was loading an old version of the DLL from the new one that was referenced in the project.

I tried out the new behavior and it appears to work well!!

Thanks, ButchersBoy.  It's appreciated!

**Comment by ButchersBoy** [comment]
:+1:
