### ISSUE TITLE
HomePage fixed and alwasy showing

### ISSUE THREAD

**Issue by nishi13** [ButchersBoy/Dragablz#75]
Hi, I`m trying to create a homepage tab that stays in place even if there is a lot of tabs opened (outside the ScrollViewer). I had 2 ideas but both failed.

-First tried to change DragablzItemsControl so it displays a DragablzItem bound to the first Item, but the clicks events were not working.
-Next try was to use the HeaderPrefix to add a fake tab with the same style, but then again I didn't know how to bind the action and the IsSelected.

**Comment by ButchersBoy** [comment]
You can use the FixedHeaderCount, but yes, this is would scroll out of view.

So yeah, the header prefix is your best bet.  You could put a ToggleButton in there, we showed a Grid which is laid over the main content of the tab control.

**Comment by nishi13** [comment]
But i still don't know what event I bind to the click and how do i know if the homepage is open because there is many ways besides clicking, for example closing a tab or dragging then out.

**Comment by nishi13** [comment]
I found the solution i used the SelectedIndex and used a trigger to set the style if the SelectedIndex is 0.

**Comment by ButchersBoy** [comment]
:+1:

**Comment by nishi13** [comment]
Hey i got another problem. The new windows that is created when dragging out a Tab must have the home page, but the problem is that when a window have 2 or more tabs when you try to drag a tab it creates a new window and this new windows have the dragged out tab and the home page. This way is impossible to drag the tab to a existing window, it always create a new window. How do I solve this?

**Comment by ButchersBoy** [comment]
dont quite understand

**Comment by nishi13** [comment]
In the ItemTabClient I've add the home page in every new Window, so every new window have 2 tabs, instead of the default that is one. And by default when you got 2 tabs in a window and try to drag the tab it creates a new window.

The only way to merge a window it to drag a window with only one tab ta a existing window.

But when i try to drag a tab it creates a new window with 2 tabs, and this window is impossible to merge merge with a existing because it have 2 tabs.

**Comment by nishi13** [comment]
One way to fix this is my home page not being really a tab.
Is there a way to unselect a tab?

**Comment by nishi13** [comment]
I fixed this by making my home page not a Tab but a control that is display above the tabs control when selected and below if not selected.
