### ISSUE TITLE
Add SNK

### ISSUE THREAD

**Issue by picrap** [ButchersBoy/Dragablz#83]
I think it's a very cheap but handy feature :smile: 
A strong named assembly would save a lot of trouble (at least to me).

**Comment by ButchersBoy** [comment]
https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/wiki/Strong-Naming

**Comment by picrap** [comment]
I have written myself a tool named SignReferences (available at NuGet), but this creates problems anyway with dependencies when there are nested dependencies... Your material design assemblies are signed, so I don't understand why this is a 'no' here. If I submit a pull request, would you accept it?

**Comment by ButchersBoy** [comment]
They aren't signed.

**Comment by ButchersBoy** [comment]
Have you tried Strong Namer? Everyone I know using it has it working fine.

**Comment by ButchersBoy** [comment]
As for dependencies I have worked hard to make sure there are no dependencies, other than standard framework.
