### ISSUE TITLE
Fixed Header Count - doesn't scroll out of view

### ISSUE THREAD

**Issue by WillCohenInfotrack** [ButchersBoy/Dragablz#85]
Hi, Is it possible to have the fixed tabs always stay  visible, no matter how many additional tabs you open?
and only have the tabs which are opened by the user affected by the scroll ?

**Comment by ButchersBoy** [comment]
I have applied a bit of thought to it...it's complicated...probably wont happen in the run up to version 1.0.0.

**Comment by WillCohenInfotrack** [comment]
Is it due to all the tabs being apart of a items presenter passed to the scroll viewer?

Is there any alternative where new tabs can overflow to a new row?

**Comment by ButchersBoy** [comment]
Yes.  And yes there is an alternative:

Use the HeaderPrefixContent.  Use this technique or a variation of:  

Put a ListBox in there with the "hard" items styled exactly to look like your tab header items.  Then, if one of those items is selected, overlay a ContentControl over the main tab content.

**Comment by WillCohenInfotrack** [comment]
Thanks for the quick replies, 

Would you have an example of this, possibly with the mahapps style :-D 
Cheers

**Comment by ButchersBoy** [comment]
Not right now unfortunately...I might try and know one up in the future, but can't say when.
