### ISSUE TITLE
Opening context menu on Tab

### ISSUE THREAD

**Issue by okatip1** [ButchersBoy/Dragablz#86]
I want to open a custom context menu when i click the tab (right click)

I couldn't find any event about that in TabablzControl or InterTabController.
(ContextMenuOpening doesnt work properly and don't return which tab i click)

Is this possible now? If it's not, how we can implement that?

**Comment by ButchersBoy** [comment]
You mean on each individual tab header right?  Or on the main content?

**Comment by okatip1** [comment]
Yes exactly, on each individual tab header. Not the main content.
17 Şub 2016 10:56 tarihinde "James Willock" <notifications@github.com>
yazdı:

**Comment by ButchersBoy** [comment]
The underlying Thumb control wasn't allowing right -clicks to pass through, so I've fixed this and expanded on one of the demos to show a context menu in use.

https://github.com/ButchersBoy/Dragablz/blob/master/DragablzDemo/QuickStartWindow.xaml#L26

**Comment by okatip1** [comment]
Thanks for your support.

But,

I'm using the BoundExampleWindow. And in xaml there is no TabItem.

I want to create and open a context menu in code behind when I click a tab (right click)

So I need the clicked(right) tab in code behind in BoundExampleWindow.

There are two problems in here:
1-) There is no event that I'm enable to get the clicked(right) tab in TabablzControl.
2-) **TabControl.Items[index]** type is datatemplate type, not the **TabItem**. How can I get the TabItem if it is nessesary on BoundExampleWindow

**Comment by ButchersBoy** [comment]
You don't need a TabItem.  Using the BoundExampleWindow example, you need to set the ```TabablzControl.CustomerHeaderItemTemplate```, to something like this:
```
                <Grid>
                    <Grid.ContextMenu>
                        <ContextMenu>
                            <MenuItem Header="Hello World" />
                        </ContextMenu>
                    </Grid.ContextMenu>
                    <ContentControl Content="{Binding }" FontSize="14" />
                </Grid>
```

Which will give you this.  

![image](https://cloud.githubusercontent.com/assets/658107/13113575/7f29447e-d587-11e5-8c8f-e56327e3aa78.png)

I'm assuming you are wanting a more MVVM effect, so you could then remove (and adjust the main content to display the tab name by binding to a property name on your view model):
```
<Setter Property="HeaderMemberPath" Value="Header" />
```
And bind your MenuItems to ICommands on your view model.

**Comment by ButchersBoy** [comment]
Although I might make CustomHeaderItemTemplate obsolete in favour of HeaderItemTemplate
