### ISSUE TITLE
Crash in DragablzColors

### ISSUE THREAD

**Issue by thoemmi** [ButchersBoy/Dragablz#88]
`DragablzColors` crashes on my machine, maybe because I'm running **Windows 10 Insider Build 14271**.

The exception occurs because the parameter `percentage` to `BlendColor` is **4294967276**. This happens because in `GetBalancedWindowGlassBrush` `colorizationParams.ColorizationColorBalance` is **120**, and 100-120 is 4294967276 in unsigned integer arithmetic.

**Comment by ButchersBoy** [comment]
I guess even if it was an int 120-100 wouldn't be much good either...I'll run it up on a couple of normal Windows 10 machines, and maybe just add a floor/ceiling...
