### ISSUE TITLE
Need to know whether Dragablz or the user is closing a window

### ISSUE THREAD

**Issue by RolandPheasant** [ButchersBoy/Dragablz#9]
There is a need to know whether dragablz is closing a window because a user is dragging, or whether a window is being closed due to the user pressing the close button.

This is required as I am binding to disposable view models which of course need to be disposed correctly.

This can be replicated using this https://github.com/RolandPheasant/TradingDemo. Open some windows and drag one window out and pop it back into a side dock. You will see that the menu buttons stop working.

**Comment by ButchersBoy** [comment]
Gotcha.

**Comment by ButchersBoy** [comment]
Added a new non-bindable attached property which you can query:

`TabablzControl.GetIsClosingAsPartOfDragOperation(window)`

I added this into your demo and created a pull request.

**Comment by salman-cs** [comment]
The child content can close the tab?
