### ISSUE TITLE
Unable to add a button to a TabItem

### ISSUE THREAD

**Issue by xxMUROxx** [ButchersBoy/Dragablz#92]
I am unable to add a button to a **HeaderTemplate** of a **TabItem**. It is not clickable by default.
If I rightclick and let this mouse-key clicked, then the button is clickable with the left mouse key.
Is that by design?
~~~
<dragablz:TabablzControl.HeaderItemTemplate>
  <DataTemplate DataType="cinch:WorkspaceData">
    <StackPanel Orientation="Horizontal" IsHitTestVisible="True">
      <TextBlock Text="{Binding Path=DisplayText,Mode=OneTime}" />
      <Button Text="{Binding Path=DisplayText,Mode=OneTime}" />
    </StackPanel>
  </DataTemplate>
</dragablz:TabablzControl.HeaderItemTemplate>
~~~
Below you see a GIF. The Pin button is visible when **IsMouseOver** is **true** or the ToggleButton (i.e. the pin) is checked
![animation](https://cloud.githubusercontent.com/assets/4341039/13572226/7582ec1c-e479-11e5-87ae-cf0e7dcbab82.gif)

**Comment by ButchersBoy** [comment]
Yes, it's by design, as there is a Thumb to handle
 the dragging. However, you can provide a custom thumb when you want to create more complex tabs. Check out the demo tab which has a checkbox in it, this shows your how to do it.

**Comment by ButchersBoy** [comment]
Please refer to this part of the demo:

https://github.com/ButchersBoy/Dragablz/blob/master/DragablzDemo/CustomHeader.xaml

**Comment by xxMUROxx** [comment]
Thanks @ButchersBoy that was the solution.
