### ISSUE TITLE
Issue with Prism 

### ISSUE THREAD

**Issue by totone69** [ButchersBoy/Dragablz#94]
Hi.
First of all thanks so much for your work on Dragablz and Material Design for Wpf it's absolutly great.
I recently had a problem with the tabitem behavior. I use TabablzControl as host for the RegionManager of Prism like this : `<dragablz:TabablzControl prism:RegionManager.RegionName="MainRegion" >` and I put my modules in a folder and my module Catalog stacks it into the TabablzControl on the loading time. It work fine but the header of the tabitem doesn't find the title of the loaded module. However  I have got this code for bind the Title and it work great with the standard component and also with the mahapps tabcontrol but not here :  
`<dragablz:TabablzControl.Resources>
                <Style TargetType="TabItem"  BasedOn="{StaticResource {x:Type TabItem}}">
                    <Setter Property="Header" 
                    Value="{Binding RelativeSource={RelativeSource Self}, 
                Path=Content.DataContext.TitreModule}" />
                </Style>
            </dragablz:TabablzControl.Resources>`
Have you any idea about this issue ?
Thanks

**Comment by ButchersBoy** [comment]
Easiest if you can post a sample repo.

**Comment by totone69** [comment]
https://github.com/totone69/TestPrism

**Comment by ButchersBoy** [comment]
OK...are those the full build instructions on the Readme?  If there's any hoops I need to know up front :)

**Comment by totone69** [comment]
I'm sorry. I have just forgot to fix an compilation error when the Modules folder is not found into the Release folder. 
But normally if you have all dependencies the project should compile

**Comment by ButchersBoy** [comment]
Hi, have you looked at these Prism examples:

https://github.com/tstephansen/PrismExample
https://github.com/svantreeck/DragablzPrism

**Comment by totone69** [comment]
Thank you so much It's perfectly work  =) 
and congratulations for your work it's really impressive.
