### ISSUE TITLE
Issue with mupltiple screens

### ISSUE THREAD

**Issue by Omilis** [ButchersBoy/Dragablz#95]
Hi,
There is an issue with creating a new window by dragging if there is more than one screen and current window is maximized. If I maximize window on secondary screen and I drag out a tab, new window appears on primary screen. It looks like it has correct offset from top-left corner and it moves relative to the mouse, but it is on the wrong screen.

Thanks

**Comment by Flozi95** [comment]
I also got this problem :+1:

**Comment by sabellefallEFC** [comment]
We also have this problem ! We would love if it could get corrected as it prevents us from putting Dragablz on our main project.
